version: '3'
services:
  np-vue-builder:
    build:
      context: .
      dockerfile: frontend.dockerfile
    container_name: np_vue_builder
    env_file:
      - nodejs.env
    volumes:
      - ./deploy_www:/var/www/html

  np-composer:
    restart: 'no'
    container_name: np_composer
    build:
      context: .
      dockerfile: composer.dockerfile
    volumes:
      - ./backend/protected:/var/www/html

  np-app:
    build:
      context: .
      dockerfile: backend.dockerfile
    container_name: np_app
    volumes:
      - ./deploy_www:/var/www/html
      - ./backend:/var/www/html/api
      - ./frontend/public/.htaccess:/var/www/html/.htaccess
    env_file:
      - apache.env
    ports:
      - '80:80'

  mysql:
    container_name: np_mysql
    image: mariadb
    env_file:
      - mysql.env
    ports:
    - '3305:3306'
    volumes:
      - ./mysql/data:/mysql/data
      - ./mysql_init:/docker-entrypoint-initdb.d

networks:
  default:
    driver: bridge