version: '3'
services:
  np-vue-builder:
    build:
      context: .
      dockerfile: frontend.dockerfile
    container_name: np_vue_builder
    volumes:
      - ./deploy_www:/var/www/html

  np-composer:
    restart: 'no'
    container_name: np_composer
    image: composer:latest
    working_dir: /var/www/html
    command: composer install -d /var/www/html
    volumes:
      - ./backend/protected:/var/www/html

  np-app:
    build:
      context: .
      dockerfile: backend.dockerfile
    container_name: np_app
    volumes:
      - ./deploy_www:/var/www/html
      - ./backend:/var/www/html/api
    environment:
      DB_HOST: mysql
      DB_USERNAME: root
      DB_PASSWORD: oasdasomdasdmo
    ports:
      - '80:80'

  mysql:
    container_name: np_mysql
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=oasdasomdasdmo
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=oasdasomdasdmo
    volumes:
      - ./mysql/data:/mysql/data
      - ./mysql_init:/docker-entrypoint-initdb.d