version: '3'
services:
  np-vue-builder:
    build:
      context: .
      dockerfile: frontend.dockerfile
    container_name: np_vue_builder
    volumes:
      - ./deploy_www:/var/www/html

  np-app:
    build:
      context: .
      dockerfile: backend.dockerfile
    container_name: np_app
    volumes:
      - ./deploy_www:/var/www/html
      - ./backend:/var/www/html/api
      - ./custom.ini:/usr/local/etc/php/conf.d/custom.ini
    environment:
      PORT: 80
      VIRTUAL_HOST: np.strukteon.net
      LETSENCRYPT_HOST: np.strukteon.net
      LETSENCRYPT_EMAIL: sensentod@gmail.com
      DB_HOST: mysql
      DB_USERNAME: root
      DB_PASSWORD: oasdasomdasdmo
    networks:
      - nginx-sidecar
      - default

  mysql:
    container_name: np_mysql
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=oasdasomdasdmo
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=oasdasomdasdmo
    ports:
      - '3306:3306'
    volumes:
      - ./mysql/data:/mysql/data

networks:
  nginx-sidecar:
    external:
      name: letsencrypt
  default:
    driver: bridge