<template>
  <div>
    <img src="@/assets/images/dataprivacy.jpg" alt="dataprivacy" class="crop-center">
    <div>
      <div class="u1">Datenschutzerklärung</div>
    </div>
    <div class="text">
      <p style="margin-top:0pt; margin-bottom:14pt; font-size:24pt;"><strong><span>Datenschutzerkl&auml;rung</span></strong></p>
      <p style="margin-top:14pt; margin-bottom:14pt; font-size:18pt;"><strong><span>Inhaltsverzeichnis</span></strong></p>
      <ul style="margin:0pt; padding-left:0pt;" type="disc">
        <li style="margin-top:14pt; margin-left:27.6pt; padding-left:8.4pt; font-family:serif; font-size:10pt;"><a href="#datenschutz" style="text-decoration:none;"><u><span style="font-family:'Times New Roman'; font-size:12pt; color:#0000ff;">Datenschutz</span></u></a><span style="font-family:'Times New Roman'; font-size:12pt;">&nbsp;</span></li>
        <li style="margin-left:27.6pt; padding-left:8.4pt; font-family:serif; font-size:10pt;"><a href="#automatische-datenspeicherung" style="text-decoration:none;"><u><span style="font-family:'Times New Roman'; font-size:12pt; color:#0000ff;">Automatische Datenspeicherung</span></u></a><span style="font-family:'Times New Roman'; font-size:12pt;">&nbsp;</span></li>
        <li style="margin-left:27.6pt; padding-left:8.4pt; font-family:serif; font-size:10pt;"><a href="#cookies" style="text-decoration:none;"><u><span style="font-family:'Times New Roman'; font-size:12pt; color:#0000ff;">Cookies</span></u></a><span style="font-family:'Times New Roman'; font-size:12pt;">&nbsp;</span></li>
        <li style="margin-left:27.6pt; padding-left:8.4pt; font-family:serif; font-size:10pt;"><a href="#speicherung-persoenlicher-daten" style="text-decoration:none;"><u><span style="font-family:'Times New Roman'; font-size:12pt; color:#0000ff;">Speicherung pers&ouml;nlicher Daten</span></u></a><span style="font-family:'Times New Roman'; font-size:12pt;">&nbsp;</span></li>
        <li style="margin-left:27.6pt; padding-left:8.4pt; font-family:serif; font-size:10pt;"><a href="#rechte-dsgvo" style="text-decoration:none;"><u><span style="font-family:'Times New Roman'; font-size:12pt; color:#0000ff;">****** laut Datenschutzgrundverordnung</span></u></a><span style="font-family:'Times New Roman'; font-size:12pt;">&nbsp;</span></li>
        <li style="margin-left:27.6pt; padding-left:8.4pt; font-family:serif; font-size:10pt;"><a href="#tls-verschluesselung-https" style="text-decoration:none;"><u><span style="font-family:'Times New Roman'; font-size:12pt; color:#0000ff;">TLS-Verschl&uuml;sselung mit https</span></u></a><span style="font-family:'Times New Roman'; font-size:12pt;">&nbsp;</span></li>
        <li style="margin-left:27.6pt; padding-left:8.4pt; font-family:serif; font-size:10pt;"><a href="#google-analytics-datenschutzerklaerung" style="text-decoration:none;"><u><span style="font-family:'Times New Roman'; font-size:12pt; color:#0000ff;">Google Analytics Datenschutzerkl&auml;rung</span></u></a><span style="font-family:'Times New Roman'; font-size:12pt;">&nbsp;</span></li>
        <li style="margin-left:27.6pt; padding-left:8.4pt; font-family:serif; font-size:10pt;"><a href="#e-mail-marketing" style="text-decoration:none;"><u><span style="font-family:'Times New Roman'; font-size:12pt; color:#0000ff;">E-Mail-Marketing</span></u></a><span style="font-family:'Times New Roman'; font-size:12pt;">&nbsp;</span></li>
        <li style="margin-left:27.6pt; padding-left:8.4pt; font-family:serif; font-size:10pt;"><a href="#social-media" style="text-decoration:none;"><u><span style="font-family:'Times New Roman'; font-size:12pt; color:#0000ff;">Social Media</span></u></a><span style="font-family:'Times New Roman'; font-size:12pt;">&nbsp;</span></li>
        <li style="margin-left:27.6pt; padding-left:8.4pt; font-family:serif; font-size:10pt;"><a href="#instagram-datenschutzerklaerung" style="text-decoration:none;"><u><span style="font-family:'Times New Roman'; font-size:12pt; color:#0000ff;">Instagram Datenschutzerkl&auml;rung</span></u></a><span style="font-family:'Times New Roman'; font-size:12pt;">&nbsp;</span></li>
        <li style="margin-left:27.6pt; margin-bottom:14pt; padding-left:8.4pt; font-family:serif; font-size:10pt;"><a href="#google-recaptcha-datenschutzerklaerung" style="text-decoration:none;"><u><span style="font-family:'Times New Roman'; font-size:12pt; color:#0000ff;">****** reCAPTCHA Datenschutzerkl&auml;rung</span></u></a><span style="font-family:'Times New Roman'; font-size:12pt;">&nbsp;</span></li>
      </ul>
      <p style="margin-top:14pt; margin-bottom:14pt; font-size:18pt;"><strong><span>Datenschutz</span></strong></p>
      <p><span>Wir ***** diese Datenschutzerkl&auml;**** (******* 04.05.2021-111735732) verfasst, um Ihnen gem&auml;&szlig; der Vorgaben der&nbsp;</span><a href="https://eur-lex.europa.eu/legal-content/DE/ALL/?uri=celex%3A32016R0679&tid=111735732" style="text-decoration:none;" target="_blank"><u><span style="font-family:'Times New Roman'; color:#0000ff;">Datenschutz-Grundverordnung (EU) 2016/679</span></u></a><span>&nbsp;und *********** nationalen Gesetzen zu erkl&auml;ren, welche personenbezogenen Daten *** verarbeiten, zuk&uuml;nftig *********** werden *** welche rechtm&auml;&szlig;igen Entscheidungsm&ouml;glichkeiten *** als Besucher ****** Webseite haben.</span></p>
      <p><span>Datenschutzerkl&auml;rungen ******* f&uuml;r gew&ouml;****** sehr technisch. Diese Version soll Ihnen hingegen die wichtigsten Dinge so einfach und klar *** m&ouml;glich beschreiben. Soweit es m&ouml;glich ist, ****** technische ******** leserfreundlich erkl&auml;rt. Au&szlig;***** m&ouml;chten wir vermitteln, dass wir *** dieser Website *** dann Informationen sammeln und verwenden, wenn eine entsprechende gesetzliche Grundlage ******* ist. Das *** sicher nicht m&ouml;glich, **** man m&ouml;glichst knappe, technische Erkl&auml;rungen abgibt, so wie sie im Internet oft ******** sind, wenn es um Datenschutz geht. Ich hoffe Sie finden die folgenden Erl&auml;********* interessant und informativ *** vielleicht ist die eine oder andere Information dabei, die Sie noch nicht kannten.</span><br><span>Wenn trotzdem Fragen bleiben, m&ouml;chten wir Sie bitten den vorhandenen Links zu ****** und sich weitere Informationen auf *********** anzusehen, oder uns einfach eine E-**** zu schreiben. Unsere Kontaktdaten finden Sie im Impressum.</span></p>
      <p style="margin-top:14pt; margin-bottom:14pt; font-size:18pt;"><strong><span>Automatische Datenspeicherung</span></strong></p>
      <p><span>**** Sie heutzutage Websites besuchen, werden ******* Informationen *********** erstellt und gespeichert, so auch auf dieser Website. Diese gesammelten Daten sollten m&ouml;glichst sparsam und nur mit Begr&uuml;ndung gesammelt werden werden. Mit Website meinen *** &uuml;brigens die Gesamtheit aller Webseiten auf Ihrer Domain, d.h. alles von der Startseite (Homepage) bis hin *** aller letzten Unterseite (wie dieser hier). Mit Domain meinen wir zum Beispiel beispiel.de oder musterbeispiel.com.</span></p>
      <p><span>Auch w&auml;hrend Sie ****** Website jetzt gerade besuchen, speichert unser Webserver &ndash; das *** der Computer auf dem diese Webseite gespeichert ist &ndash;</span><span>&nbsp;</span><span>&nbsp;aus Gr&uuml;nden der Betriebssicherheit, zur Erstellung von Zugriffsstatistik usw. in der Regel automatisch Daten wie</span></p>
      <ul style="margin:0pt; padding-left:0pt;" type="disc">
        <li style="margin-top:14pt; margin-left:27.6pt; padding-left:8.4pt; font-family:serif; font-size:10pt;"><span style="font-family:'Times New Roman'; font-size:12pt;">die komplette Internetadresse (URL) der aufgerufenen Webseite (z. B. https://www.beispielwebsite.de/beispielunterseite.html/)</span></li>
        <li style="margin-left:27.6pt; padding-left:8.4pt; font-family:serif; font-size:10pt;"><span style="font-family:'Times New Roman'; font-size:12pt;">Browser und Browserversion (z. B. Chrome 87)</span></li>
        <li style="margin-left:27.6pt; padding-left:8.4pt; font-family:serif; font-size:10pt;"><span style="font-family:'Times New Roman'; font-size:12pt;">das ********** Betriebssystem (z. B. Windows 10)</span></li>
        <li style="margin-left:27.6pt; padding-left:8.4pt; font-family:serif; font-size:10pt;"><span style="font-family:'Times New Roman'; font-size:12pt;">die Adresse (URL) *** zuvor besuchten Seite (******** URL) (z. B. https://www.beispielquellsite.de/vondabinichgekommen.html/)</span></li>
        <li style="margin-left:27.6pt; padding-left:8.4pt; font-family:serif; font-size:10pt;"><span style="font-family:'Times New Roman'; font-size:12pt;">*** Hostname und die IP-Adresse des Ger&auml;ts *** welchem aus zugegriffen **** (z. B. COMPUTERNAME und 194.23.43.121)</span></li>
        <li style="margin-left:27.6pt; padding-left:8.4pt; font-family:serif; font-size:10pt;"><span style="font-family:'Times New Roman'; font-size:12pt;">Datum und Uhrzeit</span></li>
        <li style="margin-left:27.6pt; margin-bottom:14pt; padding-left:8.4pt; font-family:serif; font-size:10pt;"><span style="font-family:'Times New Roman'; font-size:12pt;">in Dateien, *** sogenannten Webserver-Logfiles.</span></li>
      </ul>
      <p><span style="height:0pt; margin-top:-14pt; display:block; position:absolute; z-index:0;"><img src="https://myfiles.space/user_files/85721_00c7a66483f4b880/1620157638_datenschutzerklarung/1620157638_datenschutzerklarung.001.png" alt="Browser und Webserver" width="605" height="605" style="margin: 0 auto 0 0; text-align: left; display: block; "></span><span>Zur Veranschaulichung:</span></p>
      <p><img src="https://myfiles.space/user_files/85721_00c7a66483f4b880/1620157638_datenschutzerklarung/1620157638_datenschutzerklarung.002.png" alt="" width="605" height="154"></p>
      <p><span>In der Regel ****** diese Dateien zwei Wochen gespeichert und danach *********** gel&ouml;scht. *** geben diese ***** nicht weiter, k&ouml;**** jedoch nicht ausschlie&szlig;en, dass diese Daten beim Vorliegen *** rechtswidrigem ********* von Beh&ouml;rden ********** werden.</span></p>
      <p><span>**** gesagt: Ihr Besuch wird durch unseren Provider (Firma, die unsere Website auf speziellen Computern (Servern) laufen l&auml;sst), protokolliert, aber wir geben Ihre Daten nicht weiter!</span></p>
      <p style="margin-top:14pt; margin-bottom:14pt; font-size:18pt;"><strong><span>Cookies</span></strong></p>
      <p><span>Unsere Webseite verwendet HTTP-Cookies, um nutzerspezifische Daten zu speichern.</span><br><span>Im Folgenden erkl&auml;ren wir, *** Cookies sind und warum *** genutzt werden, damit Sie die ******** Datenschutzerkl&auml;rung ****** verstehen.</span></p>
      <p style="margin-top:14pt; margin-bottom:14pt; font-size:13.5pt;"><strong><span>Was genau sind Cookies?</span></strong></p>
      <p><span>Immer wenn Sie ***** das Internet surfen, verwenden *** ***** Browser. Bekannte Browser sind beispielsweise Chrome, Safari, Firefox, Internet Explorer und Microsoft Edge. Die meisten Webseiten speichern ****** Text-Dateien ** Ihrem Browser. ***** Dateien nennt man Cookies.</span></p>
      <p><span>Eines ist nicht von der Hand zu weisen: Cookies sind **** n&uuml;******* Helferlein. Fast alle Webseiten verwenden</span><span>&nbsp;</span><span>Cookies. Genauer gesprochen sind es HTTP-Cookies, da es auch noch andere Cookies f&uuml;r ****** Anwendungsbereiche gibt. HTTP-Cookies</span><span>&nbsp;</span><span>sind kleine Dateien, die von unserer Webseite *** ***** Computer gespeichert werden. ***** Cookie-Dateien ****** *********** ** Cookie-Ordner, quasi *** &ldquo;Hirn&rdquo; Ihres Browsers, untergebracht. Ein Cookie besteht aus einem Namen und einem Wert. Bei der Definition ***** Cookies m&uuml;ssen zus&auml;****** ein **** mehrere ********* ********* werden.</span></p>
      <p><span>Cookies</span><span>&nbsp;</span><span>speichern gewisse Nutzerdaten von Ihnen, wie beispielsweise Sprache oder pers&ouml;nliche Seiteneinstellungen. Wenn Sie ****** Seite wieder aufrufen, &uuml;bermittelt Ihr Browser *** &bdquo;userbezogenen&ldquo; Informationen an unsere Seite zur&uuml;ck. **** der Cookies wei&szlig; unsere Webseite, wer Sie sind und bietet Ihnen die Einstellung, die *** ******* sind. In einigen Browsern hat jedes</span><span>&nbsp;</span><span>Cookie</span><span>&nbsp;</span><span>**** eigene Datei, in anderen wie beispielsweise ******* sind alle</span><span>&nbsp;</span><span>Cookies</span><span>&nbsp;</span><span>in einer ******** Datei gespeichert.</span></p>
      <p><span>Die folgende Grafik zeigt eine m&ouml;gliche Interaktion zwischen einem Webbrowser wie z. B. Chrome und dem Webserver. Dabei fordert der ********** **** Website an und erh&auml;lt vom Server ein Cookie zur&uuml;ck, welches der Browser ****** verwendet, sobald eine andere ***** angefordert wird.</span></p>
      <p><img src="https://myfiles.space/user_files/85721_00c7a66483f4b880/1620157638_datenschutzerklarung/1620157638_datenschutzerklarung.003.png" alt="" width="605" height="277"></p>
      <p><span>Es gibt sowohl Erstanbieter Cookies als auch Drittanbieter-Cookies. Erstanbieter-Cookies werden direkt von unserer Seite erstellt, Drittanbieter-Cookies ****** *** Partner-Webseiten (z.B. Google Analytics) erstellt.</span><span>&nbsp;</span><span>Jedes Cookie ist individuell zu bewerten, da jedes Cookie andere Daten speichert. Auch die Ablaufzeit eines Cookies variiert von *** paar Minuten bis hin zu ein paar Jahren.</span><span>&nbsp;</span><span>Cookies sind keine Software-Programme und enthalten keine Viren, ******** oder ****** &bdquo;Sch&auml;dlinge&ldquo;. Cookies k&ouml;nnen auch nicht auf Informationen Ihres PCs zugreifen.</span></p>
      <p><span>So k&ouml;nnen zum Beispiel Cookie-Daten aussehen:</span></p>
      <p><strong><span>Name:</span></strong><span>&nbsp;_ga</span><br><strong><span>Wert:</span></strong><span>&nbsp;</span><span>GA1.2.1326744211.152111735732-9</span><br><strong><span>Verwendungszweck:</span></strong><span>&nbsp;Unterscheidung der Webseitenbesucher</span><br><strong><span>Ablaufdatum:</span></strong><span>&nbsp;</span><span>nach 2 Jahren</span></p>
      <p><span>Diese Mindestgr&ouml;&szlig;en ****** *** ******* unterst&uuml;**** k&ouml;nnen:</span></p>
      <ul style="margin:0pt; padding-left:0pt;" type="disc">
        <li style="margin-top:14pt; margin-left:27.6pt; padding-left:8.4pt; font-family:serif; font-size:10pt;"><span style="font-family:'Times New Roman'; font-size:12pt;">Mindestens 4096 Bytes pro Cookie</span></li>
        <li style="margin-left:27.6pt; padding-left:8.4pt; font-family:serif; font-size:10pt;"><span style="font-family:'Times New Roman'; font-size:12pt;">Mindestens 50 ******* *** Domain</span></li>
        <li style="margin-left:27.6pt; margin-bottom:14pt; padding-left:8.4pt; font-family:serif; font-size:10pt;"><span style="font-family:'Times New Roman'; font-size:12pt;">Mindestens 3000 Cookies insgesamt</span></li>
      </ul>
      <p style="margin-top:14pt; margin-bottom:14pt; font-size:13.5pt;"><strong><span>Welche Arten von Cookies gibt es?</span></strong></p>
      <p><span>Die Frage welche Cookies wir im Speziellen verwenden, h&auml;ngt von den verwendeten ******** ab und wird in den folgenden Abschnitten der Datenschutzerkl&auml;**** gekl&auml;rt. An dieser ****** m&ouml;chten wir kurz *** *** verschiedenen Arten von HTTP-Cookies eingehen.</span></p>
      <p><span>Man kann 4 Arten von Cookies unterscheiden:</span></p>
      <p><strong><span>Unerl&auml;******* Cookies</span></strong><br><span>Diese Cookies sind n&ouml;tig, um grundlegende Funktionen *** Webseite sicherzustellen. Zum Beispiel braucht es diese Cookies, wenn ein User ein Produkt in den Warenkorb legt, dann *** anderen Seiten weitersurft und sp&auml;ter erst zur Kasse geht. Durch diese Cookies **** der Warenkorb nicht gel&ouml;scht, selbst **** der User sein Browserfenster schlie&szlig;t.</span></p>
      <p><strong><span>Zweckm&auml;&szlig;ige Cookies</span></strong><br><span>Diese Cookies sammeln Infos &uuml;ber das Userverhalten und ob der User ******* Fehlermeldungen bekommt. ***** werden mithilfe dieser Cookies auch *** ******** *** das Verhalten der Webseite bei verschiedenen Browsern gemessen.</span></p>
      <p><strong><span>Zielorientierte Cookies</span></strong><br><span>Diese ******* sorgen f&uuml;r eine bessere Nutzerfreundlichkeit. Beispielsweise werden eingegebene Standorte, Schriftgr&ouml;&szlig;en oder Formulardaten gespeichert.</span></p>
      <p><strong><span>Werbe-Cookies</span></strong><br><span>Diese Cookies werden auch Targeting-Cookies genannt. *** dienen dazu dem **** individuell angepasste Werbung zu liefern. Das kann sehr praktisch, aber auch sehr nervig sein.</span></p>
      <p><span>&Uuml;blicherweise ****** Sie beim *********** Besuch einer ******** gefragt, welche dieser Cookiearten Sie zulassen m&ouml;chten. *** nat&uuml;rlich wird ***** Entscheidung auch in einem Cookie gespeichert.</span></p>
      <p style="margin-top:14pt; margin-bottom:14pt; font-size:13.5pt;"><strong><span>Wie kann *** Cookies l&ouml;schen?</span></strong></p>
      <p><span>Wie und ob Sie Cookies verwenden wollen, entscheiden Sie selbst. Unabh&auml;ngig von welchem Service **** welcher Webseite die Cookies stammen, haben Sie immer die M&ouml;glichkeit</span><span>&nbsp;</span><span>Cookies zu l&ouml;schen, zu deaktivieren oder nur teilweise zuzulassen. *** Beispiel k&ouml;nnen Sie Cookies von Drittanbietern blockieren, aber alle anderen Cookies zulassen.</span></p>
      <p><span>Wenn Sie feststellen m&ouml;chten, welche Cookies in Ihrem Browser gespeichert wurden, wenn Sie Cookie-Einstellungen &auml;ndern oder l&ouml;schen wollen, k&ouml;nnen Sie dies in Ihren Browser-Einstellungen finden:</span></p>
      <p><a href="https://support.google.com/chrome/answer/95647?tid=111735732" style="text-decoration:none;" target="_blank"><u><span style="font-family:'Times New Roman'; color:#0000ff;">Chrome: Cookies ** Chrome l&ouml;schen, aktivieren und verwalten</span></u></a><span>&nbsp;</span></p>
      <p><a href="https://support.apple.com/de-at/guide/safari/sfri11471/mac?tid=111735732" style="text-decoration:none;" target="_blank"><u><span style="font-family:'Times New Roman'; color:#0000ff;">Safari: Verwalten von Cookies und Websitedaten mit Safari</span></u></a><span>&nbsp;</span></p>
      <p><a href="https://support.mozilla.org/de/kb/cookies-und-website-daten-in-firefox-loschen?tid=111735732" style="text-decoration:none;" target="_blank"><u><span style="font-family:'Times New Roman'; color:#0000ff;">Firefox: Cookies l&ouml;schen, um Daten zu entfernen, die Websites auf Ihrem ******** abgelegt haben</span></u></a><span>&nbsp;</span></p>
      <p><a href="https://support.microsoft.com/de-at/help/17442/windows-internet-explorer-delete-manage-cookies?tid=111735732" style="text-decoration:none;" target="_blank"><u><span style="font-family:'Times New Roman'; color:#0000ff;">Internet Explorer: L&ouml;schen und ********* von Cookies</span></u></a><span>&nbsp;</span></p>
      <p><a href="https://support.microsoft.com/de-at/help/4027947/windows-delete-cookies?tid=111735732" style="text-decoration:none;" target="_blank"><u><span style="font-family:'Times New Roman'; color:#0000ff;">Microsoft Edge: L&ouml;schen und Verwalten von Cookies</span></u></a><span>&nbsp;</span></p>
      <p><span>Falls Sie grunds&auml;tzlich keine ******* haben wollen, k&ouml;nnen Sie Ihren ******* so einrichten, dass er Sie ***** informiert, wenn *** Cookie ******* werden soll. So k&ouml;nnen Sie bei jedem ********* Cookie entscheiden, ob Sie das Cookie erlauben oder nicht. Die ************* ist ** nach ******* verschieden. Am besten Sie suchen die Anleitung ** Google mit dem Suchbegriff &ldquo;Cookies l&ouml;schen Chrome&rdquo; oder &ldquo;Cookies deaktivieren Chrome&rdquo; ** Falle eines Chrome Browsers.</span></p>
      <p style="margin-top:14pt; margin-bottom:14pt; font-size:13.5pt;"><strong><span>Wie sieht es *** meinem Datenschutz aus?</span></strong></p>
      <p><span>Seit 2009 gibt es die sogenannten &bdquo;Cookie-Richtlinien&ldquo;. Darin ist festgehalten, dass *** Speichern von ******* eine Einwilligung von Ihnen verlangt. Innerhalb *** EU-L&auml;**** gibt ** allerdings noch sehr **************** Reaktionen auf diese Richtlinien. In &Ouml;sterreich erfolgte aber *** Umsetzung dieser Richtlinie ** &sect; 96 Abs. 3 des ************************** (TKG).</span><span>&nbsp;</span><span>In Deutschland wurden die Cookie-Richtlinien ***** *** ********** Recht umgesetzt. Stattdessen erfolgte die Umsetzung dieser Richtlinie weitgehend in &sect; 15 Abs.3 des Telemediengesetzes (TMG).</span></p>
      <p><span>Wenn Sie mehr &uuml;ber Cookies wissen m&ouml;chten und technische Dokumentationen nicht scheuen, empfehlen wir&nbsp;</span><a href="https://tools.ietf.org/html/rfc6265" style="text-decoration:none;" target="_blank"><u><span style="font-family:'Times New Roman'; color:#0000ff;">https://tools.ietf.org/html/rfc6265</span></u></a><span>, dem Request *** Comments der Internet *********** Task Force (IETF) ****** &ldquo;HTTP State Management Mechanism&rdquo;.</span></p>
      <p style="margin-top:14pt; margin-bottom:14pt; font-size:18pt;"><strong><span>*********** pers&ouml;******* Daten</span></strong></p>
      <p><span>Pers&ouml;nliche Daten, die Sie uns auf dieser Website elektronisch &uuml;bermitteln, wie zum Beispiel Name, E-Mail-Adresse, Adresse oder andere pers&ouml;nlichen ******* im Rahmen der &Uuml;bermittlung eines Formulars oder Kommentaren im Blog, werden von uns gemeinsam mit dem Zeitpunkt und der IP-Adresse nur zum jeweils angegebenen Zweck verwendet, sicher verwahrt *** ***** an Dritte weitergegeben.</span></p>
      <p><span>Wir nutzen Ihre pers&ouml;nlichen ***** ***** nur f&uuml;r die ************* mit jenen Besuchern, die Kontakt ausdr&uuml;****** w&uuml;nschen und f&uuml;r die Abwicklung der auf dieser Webseite angebotenen Dienstleistungen und Produkte. Wir geben Ihre pers&ouml;nlichen Daten ohne Zustimmung nicht weiter, k&ouml;nnen jedoch nicht ausschlie&szlig;en, dass diese ***** beim Vorliegen von rechtswidrigem Verhalten ********** werden.</span></p>
      <p><span>Wenn *** *** pers&ouml;nliche Daten per E-Mail schicken &ndash; somit abseits dieser Webseite &ndash; k&ouml;nnen wir keine ******* &Uuml;bertragung und den Schutz Ihrer ***** garantieren. Wir empfehlen Ihnen, vertrauliche ***** niemals unverschl&uuml;sselt per E-Mail zu &uuml;bermitteln.</span></p>
      <p style="margin-top:14pt; margin-bottom:14pt; font-size:18pt;"><strong><span>Rechte laut Datenschutzgrundverordnung</span></strong></p>
      <p><span>Ihnen ****** laut den Bestimmungen der DSGVO grunds&auml;tzlich die ******** Rechte zu:</span></p>
      <ul style="margin:0pt; padding-left:0pt;" type="disc">
        <li style="margin-top:14pt; margin-left:27.6pt; padding-left:8.4pt; font-family:serif; font-size:10pt;"><span style="font-family:'Times New Roman'; font-size:12pt;">Recht auf Berichtigung (Artikel 16 DSGVO)</span></li>
        <li style="margin-left:27.6pt; padding-left:8.4pt; font-family:serif; font-size:10pt;"><span style="font-family:'Times New Roman'; font-size:12pt;">Recht auf L&ouml;schung (&bdquo;Recht *** Vergessenwerden&ldquo;) (******* 17 DSGVO)</span></li>
        <li style="margin-left:27.6pt; padding-left:8.4pt; font-family:serif; font-size:10pt;"><span style="font-family:'Times New Roman'; font-size:12pt;">Recht auf Einschr&auml;nkung der Verarbeitung (Artikel 18 DSGVO)</span></li>
        <li style="margin-left:27.6pt; padding-left:8.4pt; font-family:serif; font-size:10pt;"><span style="font-family:'Times New Roman'; font-size:12pt;">Recht auf Benachrichtigung &ndash; Mitteilungspflicht im Zusammenhang mit der Berichtigung oder L&ouml;schung personenbezogener Daten oder der Einschr&auml;nkung der Verarbeitung (******* 19 DSGVO)</span></li>
        <li style="margin-left:27.6pt; padding-left:8.4pt; font-family:serif; font-size:10pt;"><span style="font-family:'Times New Roman'; font-size:12pt;">Recht *** Daten&uuml;bertragbarkeit (Artikel 20 DSGVO)</span></li>
        <li style="margin-left:27.6pt; padding-left:8.4pt; font-family:serif; font-size:10pt;"><span style="font-family:'Times New Roman'; font-size:12pt;">Widerspruchsrecht (******* 21 DSGVO)</span></li>
        <li style="margin-left:27.6pt; margin-bottom:14pt; padding-left:8.4pt; font-family:serif; font-size:10pt;"><span style="font-family:'Times New Roman'; font-size:12pt;">Recht, nicht einer ausschlie&szlig;lich *** einer automatisierten Verarbeitung &mdash; einschlie&szlig;lich Profiling &mdash; beruhenden Entscheidung *********** zu ****** (Artikel 22 DSGVO)</span></li>
      </ul>
      <p><span>Wenn Sie glauben, dass die Verarbeitung Ihrer Daten gegen das Datenschutzrecht verst&ouml;&szlig;t oder Ihre ********************** Anspr&uuml;che sonst in einer Weise verletzt worden sind, k&ouml;nnen *** **** bei der Aufsichtsbeh&ouml;rde beschweren. Diese ist f&uuml;r &Ouml;sterreich die Datenschutzbeh&ouml;rde, deren Webseite Sie unter&nbsp;</span><a href="https://www.dsb.gv.at/?tid=111735732" style="text-decoration:none;"><u><span style="font-family:'Times New Roman'; color:#0000ff;">https://www.dsb.gv.at/</span></u></a><span>&nbsp;finden und f&uuml;r Deutschland k&ouml;nnen Sie sich an die&nbsp;</span><a href="https://www.bfdi.bund.de" style="text-decoration:none;" target="_blank"><u><span style="font-family:'Times New Roman'; color:#0000ff;">Bundesbeauftragte f&uuml;r den Datenschutz und *** Informationsfreiheit (BfDI)</span></u></a><span>&nbsp;wenden.</span></p>
      <p style="margin-top:14pt; margin-bottom:14pt; font-size:18pt;"><strong><span>TLS-Verschl&uuml;sselung mit https</span></strong></p>
      <p><span>TLS, Verschl&uuml;******* und https klingen sehr technisch und sind es auch. Wir verwenden HTTPS (*** Hypertext ******** Protocol Secure steht f&uuml;r &bdquo;sicheres Hypertext-&Uuml;bertragungsprotokoll&ldquo;) um Daten abh&ouml;rsicher ** Internet zu &uuml;bertragen.</span><br><span>Das bedeutet, dass die komplette &Uuml;bertragung aller Daten von ***** Browser zu ******* Webserver abgesichert *** &ndash; niemand kann &ldquo;mith&ouml;ren&rdquo;.</span></p>
      <p><span>Damit haben wir eine zus&auml;tzliche Sicherheitsschicht eingef&uuml;hrt und erf&uuml;**** Datenschutz durch Technikgestaltung&nbsp;</span><a href="https://eur-lex.europa.eu/legal-content/DE/TXT/HTML/?uri=CELEX:32016R0679&from=DE&tid=111735732" style="text-decoration:none;" target="_blank"><u><span style="font-family:'Times New Roman'; color:#0000ff;">Artikel 25 Absatz 1 DSGVO</span></u></a><span>). Durch den ******* von TLS (Transport Layer Security), einem Verschl&uuml;sselungsprotokoll zur sicheren Daten&uuml;bertragung im Internet k&ouml;nnen wir den ****** vertraulicher ***** sicherstellen.</span><br><span>Sie ******** die Benutzung ****** Absicherung der Daten&uuml;bertragung am kleinen Schlosssymbol&nbsp;</span><img src="https://myfiles.space/user_files/85721_00c7a66483f4b880/1620157638_datenschutzerklarung/1620157638_datenschutzerklarung.004.png" alt="" width="17" height="19"><span>&nbsp;</span><span>links oben im Browser links von *** *************** (z. B. beispielseite.de) und der Verwendung des Schemas https (anstatt http) als Teil unserer Internetadresse.</span><br><span>Wenn Sie mehr zum ***** Verschl&uuml;sselung wissen m&ouml;chten, ********* wir die Google Suche nach &ldquo;********* Transfer Protocol Secure wiki&rdquo; um gute ***** zu weiterf&uuml;hrenden Informationen zu erhalten.</span></p>
      <p style="margin-top:14pt; margin-bottom:14pt; font-size:18pt;"><strong><span>Google ********* Datenschutzerkl&auml;rung</span></strong></p>
      <p><span>Wir verwenden auf unserer Website das Analyse-Tracking Tool ****** Analytics (GA) des amerikanischen Unternehmens Google Inc. F&uuml;r den europ&auml;ischen Raum ist das *********** ****** Ireland Limited (Gordon House, ****** ****** ****** 4, Irland) f&uuml;r alle Google-Dienste verantwortlich. Google ********* sammelt Daten &uuml;*** **** Handlungen auf unserer Website. Wenn Sie beispielsweise ***** Link anklicken, wird diese Aktion in einem Cookie *********** und an Google Analytics versandt. Mithilfe der Berichte, die wir von Google ********* erhalten, k&ouml;nnen *** unsere Website und unser Service besser an Ihre W&uuml;nsche anpassen. Im Folgenden gehen wir n&auml;her auf *** Tracking-Tool ein und informieren Sie vor allem dar&uuml;ber, welche Daten gespeichert werden und wie Sie das verhindern k&ouml;nnen.</span></p>
      <p style="margin-top:14pt; margin-bottom:14pt; font-size:13.5pt;"><strong><span>Was ist ****** Analytics?</span></strong></p>
      <p><span>Google Analytics ist ein Trackingtool, das der Datenverkehrsanalyse unserer Website dient. Damit ****** Analytics funktioniert, **** ein Tracking-Code in den Code unserer Website eingebaut. Wenn Sie unsere Website besuchen, zeichnet dieser **** ************ ********** auf, die Sie *** unserer Website ausf&uuml;hren. Sobald Sie unsere Website verlassen, werden diese Daten an *** Google-Analytics-Server gesendet und dort gespeichert.</span></p>
      <p><span>Google verarbeitet die Daten und wir bekommen ******** &uuml;*** Ihr Userverhalten. Dabei kann es sich unter anderem um folgende Berichte handeln:</span></p>
      <ul style="margin:0pt; padding-left:0pt;" type="disc">
        <li style="margin-top:14pt; margin-left:27.6pt; padding-left:8.4pt; font-family:serif; font-size:10pt;"><span style="font-family:'Times New Roman'; font-size:12pt;">Zielgruppenberichte: &Uuml;*** Zielgruppenberichte lernen wir unsere User besser kennen *** ****** genauer, *** sich f&uuml;r unser Service interessiert.</span></li>
        <li style="margin-left:27.6pt; padding-left:8.4pt; font-family:serif; font-size:10pt;"><span style="font-family:'Times New Roman'; font-size:12pt;">Anzeigeberichte: Durch Anzeigeberichte k&ouml;nnen *** unsere Onlinewerbung leichter analysieren und verbessern.</span></li>
        <li style="margin-left:27.6pt; padding-left:8.4pt; font-family:serif; font-size:10pt;"><span style="font-family:'Times New Roman'; font-size:12pt;">Akquisitionsberichte: Akquisitionsberichte geben uns hilfreiche Informationen dar&uuml;ber, wie wir mehr ******** f&uuml;r unser Service begeistern k&ouml;nnen.</span></li>
        <li style="margin-left:27.6pt; padding-left:8.4pt; font-family:serif; font-size:10pt;"><span style="font-family:'Times New Roman'; font-size:12pt;">Verhaltensberichte: Hier erfahren wir, wie Sie *** unserer Website interagieren. Wir k&ouml;nnen nachvollziehen welchen Weg Sie auf unserer Seite zur&uuml;******* und welche Links Sie anklicken.</span></li>
        <li style="margin-left:27.6pt; padding-left:8.4pt; font-family:serif; font-size:10pt;"><span style="font-family:'Times New Roman'; font-size:12pt;">Conversionsberichte: Conversion nennt man einen Vorgang, bei dem Sie ******** einer Marketing-Botschaft **** gew&uuml;nschte Handlung ausf&uuml;hren. Zum Beispiel, wenn Sie von ***** reinen Websitebesucher zu einem K&auml;ufer oder Newsletter-Abonnent werden. ******** ****** Berichte erfahren wir mehr dar&uuml;ber, wie unsere Marketing-Ma&szlig;nahmen *** Ihnen ankommen. So ****** wir unsere Conversionrate steigern.</span></li>
        <li style="margin-left:27.6pt; margin-bottom:14pt; padding-left:8.4pt; font-family:serif; font-size:10pt;"><span style="font-family:'Times New Roman'; font-size:12pt;">Echtzeitberichte: Hier ******** *** immer sofort, was gerade *** unserer Website passiert. Zum Beispiel sehen wir wie viele User gerade ****** Text lesen.</span></li>
      </ul>
      <p style="margin-top:14pt; margin-bottom:14pt; font-size:13.5pt;"><strong><span>Warum verwenden wir Google Analytics *** unserer Webseite?</span></strong></p>
      <p><span>Unser Ziel mit dieser Website ist klar: Wir wollen Ihnen das bestm&ouml;gliche Service bieten. Die Statistiken *** ***** von Google Analytics helfen uns ****** **** ** erreichen.</span></p>
      <p><span>*** statistisch ************* ***** zeigen uns ein klares Bild von den St&auml;**** und Schw&auml;chen unserer Website. Einerseits k&ouml;nnen wir unsere Seite so optimieren, dass sie *** interessierten Menschen auf Google leichter gefunden wird. Andererseits helfen uns die Daten, Sie als Besucher besser zu verstehen. Wir wissen somit **** genau, was wir an unserer Website verbessern m&uuml;ssen, um Ihnen das bestm&ouml;gliche Service zu bieten. Die Daten ****** uns auch, unsere Werbe- und Marketing-Ma&szlig;****** individueller *** kosteng&uuml;nstiger durchzuf&uuml;hren. Schlie&szlig;**** ***** es nur Sinn, unsere Produkte und Dienstleistungen Menschen ** zeigen, die **** daf&uuml;r interessieren.</span></p>
      <p style="margin-top:14pt; margin-bottom:14pt; font-size:13.5pt;"><strong><span>Welche Daten werden von ****** Analytics gespeichert?</span></strong></p>
      <p><span>Google Analytics erstellt ******** eines Tracking-Codes eine zuf&auml;llige, eindeutige ID, die mit Ihrem Browser-Cookie verbunden ist. So erkennt Sie Google Analytics *** ***** User. Wenn Sie das n&auml;chste Mal unsere Seite besuchen, werden Sie als &bdquo;wiederkehrender&ldquo; User erkannt. Alle gesammelten Daten werden gemeinsam mit dieser User-ID gespeichert. So ist es &uuml;berhaupt erst m&ouml;glich pseudonyme Userprofile auszuwerten.</span></p>
      <p><span>Um mit ****** Analytics ****** Website analysieren zu k&ouml;nnen, muss eine Property-** in den Tracking-Code eingef&uuml;gt werden. Die Daten werden dann ** der entsprechenden Property gespeichert. F&uuml;r jede neu angelegte Property *** die ****** Analytics 4-Property standardm&auml;&szlig;ig. ********** kann man aber **** noch die Universal Analytics Property erstellen. Je nach *********** Property ****** Daten unterschiedlich lange gespeichert.</span></p>
      <p><span>Durch Kennzeichnungen wie Cookies und App-Instanz-IDs werden Ihre Interaktionen auf ******* Website gemessen. Interaktionen **** alle ***** *** Handlungen, die Sie auf ******* ******* ausf&uuml;hren. Wenn Sie auch andere Google-******* (wie z.B. ein Google-Konto) n&uuml;tzen, k&ouml;nnen &uuml;*** Google Analytics generierte Daten mit Drittanbieter-Cookies verkn&uuml;*** werden. Google gibt keine Google Analytics-Daten weiter, au&szlig;er *** *** Websitebetreiber ********** das. Zu Ausnahmen kann es kommen, **** es gesetzlich ************ ist.</span></p>
      <p><span>******** Cookies werden von Google Analytics verwendet:</span></p>
      <p><strong><span>Name:</span></strong><span>&nbsp;_ga</span><br><strong><span>Wert:&nbsp;</span></strong><span>2.1326744211.152111735732-5</span><br><strong><span>Verwendungszweck:</span></strong><span>&nbsp;Standardm&auml;&szlig;ig ********* analytics.js das ****** _ga, um die User-** zu speichern. Grunds&auml;tzlich dient ** zur Unterscheidung der Webseitenbesucher.</span><br><strong><span>Ablaufdatum:</span></strong><span>&nbsp;nach 2 Jahren</span></p>
      <p><strong><span>Name:</span></strong><span>&nbsp;_gid</span><br><strong><span>Wert:&nbsp;</span></strong><span>2.1687193234.152111735732-1</span><br><strong><span>Verwendungszweck:</span></strong><span>&nbsp;</span><span>Das Cookie dient auch zur Unterscheidung der Webseitenbesucher</span><br><strong><span>Ablaufdatum:</span></strong><span>&nbsp;</span><span>**** 24 Stunden</span></p>
      <p><strong><span>Name:</span></strong><span>&nbsp;_gat_gtag_UA_</span><br><strong><span>Wert:</span></strong><span>&nbsp;1</span><br><strong><span>Verwendungszweck:</span></strong><span>&nbsp;Wird zum Senken *** Anforderungsrate verwendet. Wenn Google Analytics &uuml;ber den Google Tag Manager bereitgestellt wird, erh&auml;lt dieser Cookie den Namen _dc_gtm_ .</span><br><strong><span>Ablaufdatum:&nbsp;</span></strong><span>nach 1 Minute</span></p>
      <p><strong><span>Name:</span></strong><span>&nbsp;AMP_TOKEN</span><br><strong><span>Wert:</span></strong><span>&nbsp;***** Angaben</span><br><strong><span>Verwendungszweck:</span></strong><span>&nbsp;Das Cookie hat einen Token, *** dem eine User ID *** AMP-Client-ID-Dienst abgerufen werden kann. Andere m&ouml;gliche Werte weisen auf eine Abmeldung, eine Anfrage **** einen Fehler hin.</span><br><strong><span>Ablaufdatum:</span></strong><span>&nbsp;</span><span>nach 30 Sekunden bis zu einem Jahr</span></p>
      <p><strong><span>Name:</span></strong><span>&nbsp;__utma</span><br><strong><span>Wert:&nbsp;</span></strong><span>1564498958.1564498958.1564498958.1</span><br><strong><span>Verwendungszweck:</span></strong><span>&nbsp;Mit diesem Cookie kann man Ihr Verhalten auf der Website verfolgen und die Leistung messen. Das Cookie wird jedes Mal aktualisiert, wenn Informationen an Google Analytics gesendet werden.</span><br><strong><span>Ablaufdatum:</span></strong><span>&nbsp;nach 2 Jahren</span></p>
      <p><strong><span>Name:</span></strong><span>&nbsp;__utmt</span><br><strong><span>Wert:</span></strong><span>&nbsp;1</span><br><strong><span>Verwendungszweck:</span></strong><span>&nbsp;Das Cookie wird *** _gat_gtag_UA_ *** Drosseln der Anforderungsrate verwendet.</span><br><strong><span>Ablaufdatum:</span></strong><span>&nbsp;</span><span>**** 10 Minuten</span></p>
      <p><strong><span>Name:</span></strong><span>&nbsp;__utmb</span><br><strong><span>Wert:&nbsp;</span></strong><span>3.10.1564498958</span><br><strong><span>Verwendungszweck:</span></strong><span>&nbsp;Dieses Cookie wird verwendet, um neue Sitzungen zu bestimmen. Es wird jedes Mal aktualisiert, wenn neue Daten bzw. Infos an Google Analytics gesendet werden.</span><br><strong><span>Ablaufdatum:</span></strong><span>&nbsp;</span><span>**** 30 Minuten</span></p>
      <p><strong><span>Name:</span></strong><span>&nbsp;__utmc</span><br><strong><span>Wert:</span></strong><span>&nbsp;167421564</span><br><strong><span>Verwendungszweck:</span></strong><span>&nbsp;Dieses Cookie wird verwendet, ** neue Sitzungen f&uuml;r wiederkehrende ******** festzulegen. Dabei handelt es sich ** ein Session-Cookie und wird *** solange gespeichert, bis Sie *** Browser ****** schlie&szlig;en.</span><br><strong><span>Ablaufdatum:</span></strong><span>&nbsp;**** Schlie&szlig;*** des Browsers</span></p>
      <p><strong><span>Name:</span></strong><span>&nbsp;__utmz</span><br><strong><span>Wert:</span></strong><span>&nbsp;m|utmccn=(referral)|utmcmd=referral|utmcct=/</span><br><strong><span>Verwendungszweck:</span></strong><span>&nbsp;Das Cookie **** verwendet, um die Quelle des Besucheraufkommens *** unserer Website zu identifizieren. Das hei&szlig;t, das Cookie speichert, von wo Sie auf unsere Website gekommen sind. Das kann eine andere Seite bzw. **** Werbeschaltung gewesen sein.</span><br><strong><span>Ablaufdatum:</span></strong><span>&nbsp;nach 6 Monaten</span></p>
      <p><strong><span>Name:</span></strong><span>&nbsp;__utmv</span><br><strong><span>Wert:</span></strong><span>&nbsp;keine Angabe</span><br><strong><span>Verwendungszweck:</span></strong><span>&nbsp;Das ****** wird verwendet, um benutzerdefinierte Userdaten ** speichern. Es wird immer aktualisiert, wenn Informationen an Google Analytics gesendet werden.</span><br><strong><span>Ablaufdatum:</span></strong><span>&nbsp;nach 2 Jahren</span></p>
      <p><strong><span>Anmerkung:</span></strong><span>&nbsp;</span><span>Diese Aufz&auml;hlung kann keinen Anspruch auf Vollst&auml;ndigkeit erheben, da Google die Wahl ihrer Cookies immer wieder auch ver&auml;ndert.</span></p>
      <p><span>Hier zeigen wir Ihnen einen &Uuml;berblick &uuml;ber die wichtigsten Daten, die mit Google ********* erhoben werden:</span></p>
      <p><strong><span>Heatmaps:</span></strong><span>&nbsp;Google legt sogenannte Heatmaps an. &Uuml;*** Heatmaps sieht man genau jene Bereiche, die Sie anklicken. So bekommen wir Informationen, wo *** auf unserer Seite &bdquo;unterwegs&ldquo; sind.</span></p>
      <p><strong><span>Sitzungsdauer:</span></strong><span>&nbsp;Als ************* bezeichnet Google die Zeit, die Sie auf ******* Seite verbringen, ohne die Seite zu verlassen. **** *** 20 Minuten inaktiv waren, endet die Sitzung automatisch.</span></p>
      <p><strong><span>Absprungrate</span></strong><span>&nbsp;(engl. Bouncerate): Von einem Absprung ist die Rede, wenn Sie auf ******* Website nur eine Seite ******* und dann unsere Website wieder verlassen.</span></p>
      <p><strong><span>Kontoerstellung:</span></strong><span>&nbsp;Wenn Sie auf ******* Website ein Konto erstellen bzw. eine Bestellung machen, erhebt ****** Analytics diese Daten.</span></p>
      <p><strong><span>IP-Adresse:</span></strong><span>&nbsp;Die IP-******* wird nur in gek&uuml;rzter Form dargestellt, damit keine eindeutige Zuordnung m&ouml;glich ist.</span></p>
      <p><strong><span>Standort:</span></strong><span>&nbsp;&Uuml;ber die IP-Adresse **** das Land und Ihr ungef&auml;hrer Standort bestimmt werden. Diesen Vorgang bezeichnet man auch als IP- Standortbestimmung.</span></p>
      <p><strong><span>Technische Informationen:</span></strong><span>&nbsp;Zu *** technischen Informationen z&auml;hlen unter anderem Ihr Browsertyp, Ihr Internetanbieter oder **** Bildschirmaufl&ouml;sung.</span></p>
      <p><strong><span>Herkunftsquelle:</span></strong><span>&nbsp;Google Analytics beziehungsweise *** interessiert nat&uuml;rlich auch &uuml;ber welche Website oder welche Werbung Sie auf unsere Seite gekommen sind.</span></p>
      <p><span>Weitere ***** **** Kontaktdaten, etwaige Bewertungen, das Abspielen von ****** (z.B., **** Sie ein Video &uuml;ber unsere ***** abspielen), das Teilen *** Inhalten &uuml;ber Social Media oder das Hinzuf&uuml;gen zu Ihren Favoriten. Die Aufz&auml;hlung hat keinen Vollst&auml;***************** *** dient nur zu einer allgemeinen Orientierung der Datenspeicherung durch Google Analytics.</span></p>
      <p style="margin-top:14pt; margin-bottom:14pt; font-size:13.5pt;"><strong><span>*** lange und ** werden die Daten gespeichert?</span></strong></p>
      <p><span>Google hat Ihre ****** auf der ganzen Welt verteilt. Die meisten Server ******** sich in ******* und folglich werden Ihre Daten meist auf amerikanischen Servern gespeichert. Hier k&ouml;nnen Sie genau nachlesen wo sich die Google-Rechenzentren befinden:&nbsp;</span><a href="https://www.google.com/about/datacenters/inside/locations/?hl=de" style="text-decoration:none;" target="_blank"><u><span style="font-family:'Times New Roman'; color:#0000ff;">https://www.google.com/about/datacenters/inside/locations/?hl=de</span></u></a><span>&nbsp;</span></p>
      <p><span>Ihre Daten werden auf verschiedenen physischen Datentr&auml;gern verteilt. Das hat den Vorteil, **** die ***** ********* ******** **** und vor Manipulation besser gesch&uuml;tzt sind. In jedem Google-Rechenzentrum gibt es entsprechende **************** f&uuml;r Ihre Daten. Wenn beispielsweise die Hardware *** Google ausf&auml;llt oder Naturkatastrophen Server lahmlegen, bleibt das ****** einer Dienstunterbrechung bei Google dennoch gering.</span></p>
      <p><span>Die ****************** der Daten h&auml;ngt von den verwendeten Properties ab. Bei der Verwendung der neueren Google Analytics 4-Properties ist die Aufbewahrungsdauer Ihrer Userdaten auf 14 Monate *** eingestellt. F&uuml;r andere sogenannte Ereignisdaten haben *** die M&ouml;glichkeit eine Aufbewahrungsdauer von 2 Monaten oder 14 Monaten ** w&auml;hlen.</span></p>
      <p><span>Bei ********* Analytics-Properties ist bei Google Analytics eine Aufbewahrungsdauer Ihrer Userdaten von 26 ******* standardisiert eingestellt. Dann ****** Ihre Userdaten gel&ouml;scht. Allerdings haben wir die M&ouml;glichkeit, die Aufbewahrungsdauer von Nutzdaten selbst zu w&auml;hlen. Daf&uuml;r stehen uns f&uuml;nf ********* zur Verf&uuml;gung:</span></p>
      <ul style="margin:0pt; padding-left:0pt;" type="disc">
        <li style="margin-top:14pt; margin-left:27.6pt; padding-left:8.4pt; font-family:serif; font-size:10pt;"><span style="font-family:'Times New Roman'; font-size:12pt;">L&ouml;schung **** 14 Monaten</span></li>
        <li style="margin-left:27.6pt; padding-left:8.4pt; font-family:serif; font-size:10pt;"><span style="font-family:'Times New Roman'; font-size:12pt;">L&ouml;schung nach 26 Monaten</span></li>
        <li style="margin-left:27.6pt; padding-left:8.4pt; font-family:serif; font-size:10pt;"><span style="font-family:'Times New Roman'; font-size:12pt;">L&ouml;schung **** 38 Monaten</span></li>
        <li style="margin-left:27.6pt; padding-left:8.4pt; font-family:serif; font-size:10pt;"><span style="font-family:'Times New Roman'; font-size:12pt;">L&ouml;schung nach 50 Monaten</span></li>
        <li style="margin-left:27.6pt; margin-bottom:14pt; padding-left:8.4pt; font-family:serif; font-size:10pt;"><span style="font-family:'Times New Roman'; font-size:12pt;">***** automatische L&ouml;schung</span></li>
      </ul>
      <p><span>Zus&auml;****** gibt es auch die Option, dass Daten erst dann gel&ouml;scht werden, wenn Sie innerhalb des von *** gew&auml;***** ********* ***** mehr unsere ******* besuchen. In ****** Fall wird die Aufbewahrungsdauer jedes *** zur&uuml;ckgesetzt, wenn Sie unsere Website ********* *** festgelegten Zeitraums wieder besuchen.</span></p>
      <p><span>Wenn der *********** Zeitraum abgelaufen ist, ****** einmal ** Monat die ***** gel&ouml;scht. Diese Aufbewahrungsdauer **** f&uuml;r **** Daten, die mit Cookies, Usererkennung und Werbe-IDs (z.B. ******* der DoubleClick-Domain) verkn&uuml;pft sind. Berichtergebnisse basieren auf aggregierten Daten und werden unabh&auml;ngig *** Nutzerdaten gespeichert. Aggregierte ***** sind eine Zusammenschmelzung von Einzeldaten zu einer gr&ouml;&szlig;eren Einheit.</span></p>
      <p style="margin-top:14pt; margin-bottom:14pt; font-size:13.5pt;"><strong><span>*** kann ich meine Daten l&ouml;schen bzw. die Datenspeicherung verhindern?</span></strong></p>
      <p><span>Nach dem Datenschutzrecht der Europ&auml;ischen Union haben Sie das Recht, Auskunft &uuml;*** Ihre Daten ** erhalten, sie zu aktualisieren, zu l&ouml;schen oder einzuschr&auml;nken. ******** des Browser-Add-ons zur Deaktivierung von Google Analytics-JavaScript (ga.js, analytics.js, dc.js) verhindern Sie, dass Google Analytics Ihre Daten verwendet. Das Browser-Add-on k&ouml;nnen Sie unter&nbsp;</span><a href="https://tools.google.com/dlpage/gaoptout?hl=de" style="text-decoration:none;" target="_blank"><u><span style="font-family:'Times New Roman'; color:#0000ff;">https://tools.google.com/dlpage/gaoptout?hl=de</span></u></a><span>&nbsp;*********** *** installieren. Beachten Sie bitte, dass durch dieses Add-on nur die ************* durch Google Analytics deaktiviert wird.</span></p>
      <p><span>Falls Sie grunds&auml;tzlich Cookies (unabh&auml;ngig von ****** Analytics) deaktivieren, l&ouml;schen oder verwalten wollen, gibt ** f&uuml;r jeden Browser eine eigene Anleitung:</span></p>
      <p><a href="https://support.google.com/chrome/answer/95647?tid=111735732" style="text-decoration:none;" target="_blank"><u><span style="font-family:'Times New Roman'; color:#0000ff;">Chrome: Cookies ** Chrome l&ouml;schen, aktivieren und verwalten</span></u></a><span>&nbsp;</span></p>
      <p><a href="https://support.apple.com/de-at/guide/safari/sfri11471/mac?tid=111735732" style="text-decoration:none;" target="_blank"><u><span style="font-family:'Times New Roman'; color:#0000ff;">Safari: Verwalten von Cookies und Websitedaten *** Safari</span></u></a><span>&nbsp;</span></p>
      <p><a href="https://support.mozilla.org/de/kb/cookies-und-website-daten-in-firefox-loschen?tid=111735732" style="text-decoration:none;" target="_blank"><u><span style="font-family:'Times New Roman'; color:#0000ff;">Firefox: Cookies l&ouml;schen, um Daten zu entfernen, *** Websites auf Ihrem ******** abgelegt haben</span></u></a><span>&nbsp;</span></p>
      <p><a href="https://support.microsoft.com/de-at/help/17442/windows-internet-explorer-delete-manage-cookies?tid=111735732" style="text-decoration:none;" target="_blank"><u><span style="font-family:'Times New Roman'; color:#0000ff;">Internet Explorer: L&ouml;***** und Verwalten von Cookies</span></u></a><span>&nbsp;</span></p>
      <p><a href="https://support.microsoft.com/de-at/help/4027947/windows-delete-cookies?tid=111735732" style="text-decoration:none;" target="_blank"><u><span style="font-family:'Times New Roman'; color:#0000ff;">********* Edge: L&ouml;schen *** Verwalten von Cookies</span></u></a><span>&nbsp;</span></p>
      <p><span>Bitte beachten Sie, dass bei *** Verwendung dieses Tools Daten von Ihnen **** au&szlig;erhalb der EU gespeichert und verarbeitet werden k&ouml;nnen. Die meisten Drittstaaten (darunter auch die USA) gelten nach derzeitigem europ&auml;ischen Datenschutzrecht als nicht sicher. Daten an unsichere Drittstaaten d&uuml;rfen **** nicht einfach &uuml;bertragen, dort gespeichert und verarbeitet werden, sofern es ***** passenden Garantien (wie etwa EU-Standardvertragsklauseln) zwischen uns und *** au&szlig;ereurop&auml;ischen Dienstleister gibt.</span></p>
      <p><span>Wir hoffen wir konnten Ihnen *** wichtigsten Informationen rund um die Datenverarbeitung von Google Analytics n&auml;herbringen. **** Sie mehr &uuml;*** den Tracking-****** erfahren wollen, empfehlen wir diese beiden Links:&nbsp;</span><a href="http://www.google.com/analytics/terms/de.html" style="text-decoration:none;" target="_blank"><u><span style="font-family:'Times New Roman'; color:#0000ff;">http://www.google.com/analytics/terms/de.html</span></u></a><span>&nbsp;und&nbsp;</span><a href="https://support.google.com/analytics/answer/6004245?hl=de" style="text-decoration:none;" target="_blank"><u><span style="font-family:'Times New Roman'; color:#0000ff;">https://support.google.com/analytics/answer/6004245?hl=de</span></u></a><span>.</span></p>
      <p style="margin-top:14pt; margin-bottom:14pt; font-size:18pt;"><strong><span>Google ********* Berichte zu demografischen Merkmalen und Interessen</span></strong></p>
      <p><span>Wir ***** in Google Analytics *** Funktionen f&uuml;r Werbeberichte eingeschaltet. *** Berichte zu demografischen Merkmalen und Interessen enthalten Angaben zu Alter, Geschlecht und Interessen. Damit k&ouml;nnen wir uns &ndash; ohne diese Daten einzelnen Personen ******** zu k&ouml;nnen &ndash; ein besseres Bild von unseren Nutzern machen. **** &uuml;ber die Werbefunktionen erfahren Sie&nbsp;</span><a href="https://support.google.com/analytics/answer/3450482?hl=de_AT&utm_id=ad" style="text-decoration:none;" target="_blank"><u><span style="font-family:'Times New Roman'; color:#0000ff;">auf</span></u><u><span style="font-family:'Times New Roman'; color:#0000ff;">&nbsp;</span></u><u><span style="font-family:'Times New Roman'; color:#0000ff;">https://support.google.com/analytics/answer/3450482?hl=de_AT&amp;utm_id=ad</span></u></a><span>.</span></p>
      <p><span>Sie k&ouml;nnen die Nutzung der Aktivit&auml;ten und Informationen Ihres Google Kontos unter &ldquo;Einstellungen f&uuml;r Werbung&rdquo; auf&nbsp;</span><a href="https://adssettings.google.com/authenticated" style="text-decoration:none;"><u><span style="font-family:'Times New Roman'; color:#0000ff;">https://adssettings.google.com/authenticated</span></u></a><span>&nbsp;per Checkbox beenden.</span></p>
      <p style="margin-top:14pt; margin-bottom:14pt; font-size:18pt;"><strong><span>E-Mail-Marketing</span></strong></p>
      <p><span>Wir wollen nat&uuml;rlich mit ***** in Kontakt bleiben und Ihnen stets die wichtigsten Neuigkeiten &uuml;ber unser Unternehmen pr&auml;sentieren. Daf&uuml;r nutzen wir ***** anderem E-Mail-Marketing, *** wesentlicher Bestandteil unseres Online-Marketings. Sofern Sie sich damit einverstanden erkl&auml;ren oder es gesetzlich erlaubt ist, schicken *** Ihnen Newsletter, E-***** **** andere Benachrichtigungen. Wenn wir im folgenden Text den Begriff &bdquo;Newsletter&ldquo; verwenden, meinen wir ***** haupts&auml;chlich regelm&auml;&szlig;ig versendete E-Mails.</span></p>
      <p style="margin-top:14pt; margin-bottom:14pt; font-size:13.5pt;"><strong><span>*** melden Sie sich f&uuml;r unser E-Mail-Marketing an?</span></strong></p>
      <p><span>Wenn Sie an unserem E-Mail-Marketing (***** *** Newsletter) ********** wollen, m&uuml;ssen Sie sich im Normalfall ******* nur mit Ihrer E-Mail-Adresse anmelden. Daf&uuml;r f&uuml;llen *** ein Online-Formular aus und senden es ab. Es kann aber auch vorkommen, dass wir Sie etwa um Ihre Anrede und Ihren Namen bitten, damit wir Sie auch pers&ouml;nlich anschreiben k&ouml;nnen.</span></p>
      <p><span>Grunds&auml;tzlich funktioniert das Anmelden zu Newslettern mit Hilfe des sogenannten &bdquo;Double-Opt-In-Verfahrens&ldquo;. Nachdem Sie **** f&uuml;r unseren Newsletter auf ******* Website ********** haben, bekommen Sie eine E-Mail, &uuml;ber die Sie die Newsletter-Anmeldung best&auml;tigen. So wird sichergestellt, dass Ihnen die E-Mail-Adresse geh&ouml;rt und sich niemand mit ***** fremden E-Mail-Adresse angemeldet hat. Wir oder *** von uns verwendetes Benachrichtigungs-Tool ************* jede einzelne Anmeldung. Dies *** n&ouml;tig, damit wir den rechtlich korrekten Anmeldevorgang auch ********** k&ouml;nnen. Dabei wird ** der Regel der Zeitpunkt der Anmeldung, der Zeitpunkt der Anmeldebest&auml;tigung und Ihre IP-******* gespeichert. Zus&auml;tzlich wird **** protokolliert, wenn *** &Auml;nderungen Ihrer gespeicherten Daten vornehmen.</span></p>
      <p style="margin-top:14pt; margin-bottom:14pt; font-size:13.5pt;"><strong><span>Wie ***** d&uuml;rfen wir Ihre E-Mail-Adresse speichern?</span></strong></p>
      <p><span>Wenn *** Ihre E-Mail-Adresse aus unserem E-Mail/Newsletter-********* austragen, d&uuml;rfen wir Ihre Adresse bis zu drei Jahren *** Grundlage unserer berechtigten Interessen speichern, damit wir Ihre damalige Einwilligung **** nachweisen k&ouml;nnen. Verarbeiten d&uuml;rfen wir ***** Daten nur, wenn wir uns gegen ******* Anspr&uuml;che wehren m&uuml;ssen.</span></p>
      <p><span>**** *** ********** best&auml;tigen, dass *** uns die ************ zur Newsletter-Anmeldung gegeben haben, k&ouml;nnen Sie jederzeit einen individuellen L&ouml;schantrag stellen. Widersprechen *** der ************ dauerhaft, behalten wir uns das ***** vor, Ihre E-Mail-Adresse in ***** ********** zu speichern. ******* Sie freiwillig unseren Newsletter abonniert haben, solange behalten wir selbstverst&auml;ndlich **** Ihre E-Mail-Adresse.</span></p>
      <p style="margin-top:14pt; margin-bottom:14pt; font-size:13.5pt;"><strong><span>Auf welcher Rechtsgrundlage betreiben wir E-Mail-Marketing?</span></strong></p>
      <p><span>Das Versenden unseres Newsletters ******* auf Grundlage Ihrer Einwilligung. Das hei&szlig;t, wir d&uuml;rfen Ihnen nur dann einen ********** schicken, wenn Sie sich zuvor ***** daf&uuml;r angemeldet haben. Wenn eine Einwilligung nicht n&ouml;*** ist, dann ******* der Newsletter-******* auf ********* *** berechtigten Interesses am Direktmarketing, sofern dies ********* erlaubt ist. Auch **** *** ***** Dienstleister beauftragen, passiert dies auf der Grundlage ******* berechtigten Interesses. Ihren Registrierungsprozess ******** wir auf, damit wir stets nachweisen k&ouml;nnen, dass dieser unseren Gesetzen entspricht.</span></p>
      <p style="margin-top:14pt; margin-bottom:14pt; font-size:13.5pt;"><strong><span>Was ***** in unseren Newslettern?</span></strong></p>
      <p><span>Nat&uuml;rlich wollen wir *** mit unseren Newsletter in keiner Weise bel&auml;stigen. Darum sind *** ******** stets bem&uuml;ht, *** relevante *** interessante ******* zu bieten. So erfahren Sie etwa mehr &uuml;ber unser Unternehmen, unsere Leistungen oder Produkte. Da *** unsere Angebote **** immer verbessern, ******** Sie &uuml;ber unseren Newsletter auch immer, wenn es Neuigkeiten gibt oder wir gerade spezielle, lukrative ******** anbieten.</span></p>
      <p><span>Sofern *** einen Dienstleister, der ein professionelles Versand-Tool anbietet, f&uuml;r unser E-Mail-Marketing beauftragen, machen wir das, um Ihnen schnelle und sichere Newsletter bieten zu k&ouml;nnen.</span></p>
      <p style="margin-top:14pt; margin-bottom:14pt; font-size:13.5pt;"><strong><span>****** Daten ****** gespeichert?</span></strong></p>
      <p><span>Wenn Sie &uuml;ber unsere ******* Abonnent unseres Newsletters werden, best&auml;tigen Sie per E-Mail die ************** in einer E-Mail-Liste. ***** IP-Adresse und E-Mail-Adresse k&ouml;nnen auch Ihr Name, Ihre ******* und Ihre Telefonnummer gespeichert werden. Allerdings nur, wenn Sie dieser Datenspeicherungen zustimmen. Zus&auml;tzlich k&ouml;nnen etwa auch Informationen ** Ihrem Ger&auml;t oder zu Ihren bevorzugten Inhalten auf unserer Website gespeichert werden. Mehr zur Speicherung von Daten, wenn Sie eine Website besuchen, ****** Sie im Abschnitt &ldquo;Automatische Datenspeicherung&rdquo;.</span></p>
      <p><span>************* zu speziellen E-Mail-Marketing Diensten, erfahren Sie &ndash; ****** vorhanden &ndash; in den folgenden Abschnitten.</span></p>
      <p style="margin-top:14pt; margin-bottom:14pt; font-size:13.5pt;"><strong><span>*** kann ich mein Abo k&uuml;ndigen?</span></strong></p>
      <p><span>Sie haben jederzeit *** M&ouml;glichkeit Ihre Newsletter-Anmeldung zu k&uuml;ndigen. Daf&uuml;r m&uuml;ssen Sie lediglich Ihre Einwilligung zur Newsletter-Anmeldung widerrufen. Das ****** im Normalfall nur wenige Minuten bzw. *** **** Klicks. Meistens finden Sie direkt in unserem Newsletter einen Link, um das Abonnement ** k&uuml;ndigen. Wenn der Link im Newsletter wirklich nicht zu finden ist, kontaktieren Sie uns bitte per Mail und *** werden Ihr Newsletter-*** k&uuml;ndigen.</span></p>
      <p style="margin-top:14pt; margin-bottom:14pt; font-size:18pt;"><strong><span>Social Media</span></strong></p>
      <p><span>Zus&auml;tzlich zu unserer Website sind *** auch in Social Media aktiv. Dabei k&ouml;nnen Daten von Usern verarbeitet werden, damit wir gezielt User, die sich f&uuml;r uns interessieren, &uuml;ber *** sozialen ********* ********** k&ouml;nnen. Dar&uuml;ber hinaus k&ouml;nnen auch ******** einer Social-Media-********* direkt in unsere Website *********** sein. Das ist etwa der Fall, wenn Sie einen sogenannten Social-Button auf ******* Website anklicken und direkt zu ******* Social-Media-Auftritt weitergeleitet werden.</span></p>
      <p style="margin-top:14pt; margin-bottom:14pt; font-size:13.5pt;"><strong><span>Warum ****** *** ****** Media?</span></strong></p>
      <p><span>**** Jahren **** Social-Media-Plattformen der Ort, wo Menschen online kommunizieren *** ** Kontakt treten. Mit unseren Social-Media-Auftritten k&ouml;nnen wir unsere Produkte *** Dienstleistungen Interessenten n&auml;herbringen. Die *** unserer Website eingebundenen Social-Media-Elemente helfen Ihnen, schnell und ohne Komplikationen ** unseren Social-Media-Inhalten wechseln k&ouml;nnen.</span></p>
      <p style="margin-top:14pt; margin-bottom:14pt; font-size:13.5pt;"><strong><span>Zu ******* Zweck werden Daten ******* und gespeichert?</span></strong></p>
      <p><span>Die Daten, die durch Ihre ******* eines Social-Media-Kanals gespeichert und verarbeitet werden, dienen in erster Linie dazu, Webanalysen durchf&uuml;hren zu k&ouml;nnen. Ziel dieser Analysen ist es, ******** und personenbezogene Marketing- und Werbestrategien entwickeln ** k&ouml;nnen. Abh&auml;ngig von ***** Verhalten auf einer Social-Media-Plattform, k&ouml;nnen mit Hilfe der ausgewerteten Daten, passende R&uuml;ckschl&uuml;sse auf Ihre Interessen ********* werden und sogenannte Userprofile erstellt werden. So ist es den Plattformen auch m&ouml;glich, Ihnen ma&szlig;************* Werbeanzeigen zu pr&auml;sentieren. ******** werden f&uuml;r diesen Zweck Cookies in Ihrem Browser gesetzt, die Daten zu Ihrem ***************** speichern.</span></p>
      <p><span>***** beachten Sie, dass *** der Nutzung *** Social-Media-Plattformen oder unserer eingebauten Elemente auch Daten *** Ihnen au&szlig;erhalb der Europ&auml;****** Union verarbeitet werden k&ouml;nnen, da viele Social-Media-Kan&auml;le, ************** Facebook oder Twitter, amerikanische *********** sind. Dadurch k&ouml;nnen Sie m&ouml;glicherweise Ihre ****** in Bezug auf Ihre personenbezogenen Daten nicht **** ** leicht einfordern bzw. durchsetzen.</span></p>
      <p style="margin-top:14pt; margin-bottom:14pt; font-size:13.5pt;"><strong><span>Welche Daten werden gespeichert?</span></strong></p>
      <p><span>Welche Daten genau gespeichert und verarbeitet werden, h&auml;*** vom jeweiligen Anbieter der Social-Media-Plattform ab. **** f&uuml;r gew&ouml;hnlich ******* es sich um ***** wie etwa Telefonnummern, E-Mailadressen, Daten, die Sie in *** Kontaktformular eingeben, Nutzerdaten *** zum Beispiel welche Buttons Sie klicken, wen Sie liken oder wem folgen, wann Sie welche Seiten besucht haben, Informationen zu Ihrem Ger&auml;t und **** IP-Adresse. Die ******* dieser Daten werden in Cookies gespeichert. Speziell **** Sie selbst ein Profil bei dem besuchten Social-Media-Kanal haben und angemeldet sind, k&ouml;nnen Daten *** ***** Profil verkn&uuml;pft werden.</span></p>
      <p><span>Alle Daten, die &uuml;ber eine Social-Media-********* erhoben werden, werden **** auf den Servern der Anbieter gespeichert. Somit haben auch nur die Anbieter Zugang zu den Daten und k&ouml;nnen Ihnen die passenden Ausk&uuml;**** geben bzw. &Auml;nderungen vornehmen.</span></p>
      <p><span>Wenn Sie genau wissen wollen, welche Daten bei *** Social-Media-Anbietern gespeichert und verarbeitet ****** und wie *** *** Datenverarbeitung widersprechen k&ouml;nnen, sollten Sie die jeweilige Datenschutzerkl&auml;rung des ************ sorgf&auml;ltig durchlesen. **** wenn *** *** Datenspeicherung und Datenverarbeitung Fragen haben oder entsprechende Rechte geltend ****** wollen, ********* wir Ihnen, sich direkt an *** Anbieter wenden.</span></p>
      <p><span>Informationen zu speziellen Social-Media-Plattformen erfahren Sie &ndash; sofern ********* &ndash; in den folgenden Abschnitten.</span></p>
      <p style="margin-top:14pt; margin-bottom:14pt; font-size:18pt;"><strong><span>Instagram Datenschutzerkl&auml;rung</span></strong></p>
      <p><span>Wir haben auf unserer ******** Funktionen von Instagram eingebaut. ********* ist eine Social Media Plattform des Unternehmens Instagram LLC, 1601 Willow Rd, Menlo Park ** 94025, USA. Instagram ist seit 2012 ein Tochterunternehmen von Facebook Inc. und geh&ouml;rt ** den Facebook-Produkten. Das Einbetten von Instagram-Inhalten auf unserer Webseite nennt man Embedding. Dadurch k&ouml;**** wir Ihnen Inhalte wie Buttons, ***** oder ****** von Instagram ****** auf ******* Webseite zeigen. **** Sie Webseiten ******* Webpr&auml;senz aufrufen, die eine Instagram-Funktion integriert haben, ****** Daten an ********* &uuml;bermittelt, gespeichert und verarbeitet. Instagram verwendet dieselben Systeme und Technologien wie Facebook. Ihre Daten werden ***** &uuml;ber alle Facebook-Firmen ****** verarbeitet.</span></p>
      <p><span>Im Folgenden wollen wir Ihnen einen genaueren Einblick geben, warum Instagram Daten sammelt, ** welche Daten ** **** handelt *** *** Sie die Datenverarbeitung weitgehend kontrollieren k&ouml;nnen. Da Instagram zu ******** Inc. geh&ouml;rt, ******** wir unsere Informationen einerseits von den Instagram-Richtlinien, andererseits allerdings auch von den Facebook-Datenrichtlinien selbst.</span></p>
      <p style="margin-top:14pt; margin-bottom:14pt; font-size:13.5pt;"><strong><span>Was *** Instagram?</span></strong></p>
      <p><span>Instagram ist eines der bekanntesten Social Media Netzwerken weltweit. Instagram kombiniert die Vorteile eines ***** *** den Vorteilen *** ************** Plattformen wie ******* oder Vimeo. Sie k&ouml;nnen *** &bdquo;Insta&ldquo; (wie viele der User die Plattform ****** nennen) Fotos und ***** Videos hochladen, mit verschiedenen Filtern ********** und **** in anderen sozialen Netzwerken verbreiten. Und wenn Sie selbst nicht aktiv sein wollen, k&ouml;nnen Sie auch nur anderen ************ Users folgen.</span></p>
      <p style="margin-top:14pt; margin-bottom:14pt; font-size:13.5pt;"><strong><span>Warum verwenden wir Instagram auf unserer Website?</span></strong></p>
      <p><span>Instagram ist jene Social Media Plattform, die in den letzten Jahren so richtig ***** die Decke ging. Und nat&uuml;***** haben auch wir auf diesen Boom reagiert. Wir wollen, **** Sie **** auf unserer Webseite ** wohl wie m&ouml;glich f&uuml;hlen. ***** ist f&uuml;r *** eine abwechslungsreiche Aufbereitung unserer Inhalte selbstverst&auml;ndlich. Durch die eingebetteten Instagram-Funktionen k&ouml;nnen wir unseren Content *** hilfreichen, lustigen oder ********** Inhalten aus der Instagram-Welt bereichern. ** Instagram eine Tochtergesellschaft von Facebook ist, k&ouml;nnen uns die erhobenen ***** auch f&uuml;r personalisierte Werbung *** Facebook dienlich sein. ** bekommen unsere Werbeanzeigen nur Menschen, die sich ******** f&uuml;r unsere Produkte **** Dienstleistungen interessieren.</span></p>
      <p><span>Instagram n&uuml;tzt die gesammelten Daten auch</span><span>&nbsp;</span><span>zu Messungs- *** Analysezwecken. Wir bekommen zusammengefasste Statistiken und so mehr Einblick &uuml;*** **** W&uuml;nsche und Interessen. Wichtig ist zu erw&auml;hnen, dass diese Berichte Sie nicht pers&ouml;nlich identifizieren.</span></p>
      <p style="margin-top:14pt; margin-bottom:14pt; font-size:13.5pt;"><strong><span>Welche Daten werden von Instagram gespeichert?</span></strong></p>
      <p><span>**** *** auf eine unserer Seiten sto&szlig;en, die Instagram-********** (wie Instagrambilder oder Plug-ins) eingebaut haben, setzt sich *** Browser automatisch mit den ******* von Instagram in Verbindung. ***** werden ***** an Instagram versandt, gespeichert und verarbeitet. *** zwar unabh&auml;ngig, ob Sie ein Instagram-***** haben oder nicht. Dazu z&auml;hlen Informationen &uuml;ber unserer Webseite, &uuml;ber ***** Computer, &uuml;ber get&auml;tigte K&auml;ufe, &uuml;ber Werbeanzeigen, die Sie sehen und wie Sie unser ******* nutzen. Weiters ****** auch Datum und Uhrzeit ***** Interaktion mit Instagram gespeichert. Wenn Sie *** Instagram-***** haben bzw. eingeloggt sind, speichert Instagram deutlich mehr Daten &uuml;ber Sie.</span></p>
      <p><span>Facebook unterscheidet zwischen Kundendaten und Eventdaten. Wir ***** davon aus, dass dies bei Instagram genau so der Fall ist. Kundendaten sind zum Beispiel Name, Adresse, Telefonnummer und IP-Adresse. Diese Kundendaten werden **** an Instagram &uuml;bermittelt werden, wenn Sie zuvor &bdquo;gehasht&ldquo; wurden. Hashing meint, ein Datensatz wird in eine Zeichenkette verwandelt. Dadurch kann man die Kontaktdaten verschl&uuml;sseln. Zudem ****** auch die oben genannten &bdquo;Event-Daten&ldquo; &uuml;bermittelt. Unter &bdquo;Event-Daten&ldquo; versteht ******** &ndash; und folglich **** Instagram &ndash; Daten &uuml;ber Ihr Userverhalten. Es kann auch vorkommen, dass Kontaktdaten mit Event-***** kombiniert werden. *** erhobenen Kontaktdaten werden mit den Daten, die Instagram bereits von Ihnen hat, abgeglichen.</span></p>
      <p><span>&Uuml;ber kleine Text-Dateien (Cookies), die meist in Ihrem Browser gesetzt werden, werden die *********** ***** an Facebook &uuml;bermittelt. Je nach *********** Instagram-Funktionen und ob Sie selbst ein Instagram-Konto haben, werden unterschiedlich ***** ***** gespeichert.</span></p>
      <p><span>Wir gehen ***** aus, dass bei Instagram die Datenverarbeitung gleich funktioniert wie bei Facebook. Das bedeutet: wenn *** ein Instagram-Konto haben oder&nbsp;</span><a href="http://www.instagram.com?tid=111735732" style="text-decoration:none;" target="_blank"><u><span style="font-family:'Times New Roman'; color:#0000ff;">www.instagram.com</span></u></a><span>&nbsp;besucht haben, hat Instagram zumindest *** Cookie gesetzt. Wenn das der Fall ist, sendet Ihr Browser &uuml;ber das Cookie Infos ** Instagram, sobald *** mit einer Instagram-Funktion in Ber&uuml;hrung kommen. Sp&auml;testens nach 90 Tagen (nach Abgleichung) werden diese Daten wieder gel&ouml;scht bzw. anonymisiert. Obwohl wir uns intensiv mit der Datenverarbeitung von Instagram besch&auml;ftigt haben, k&ouml;nnen wir nicht ganz genau sagen, welche Daten Instagram exakt ******* und speichert.</span></p>
      <p><span>Im Folgenden zeigen wir Ihnen Cookies, *** in Ihrem Browser mindestens gesetzt werden, wenn *** auf eine Instagram-Funktion (wie z.B. ****** oder ein Insta-Bild) klicken. Bei unserem Test gehen wir ***** aus, dass Sie kein Instagram-Konto haben. Wenn Sie bei Instagram eingeloggt sind, werden nat&uuml;***** deutlich **** Cookies in Ihrem Browser gesetzt.</span></p>
      <p><span>Diese Cookies wurden bei unserem Test verwendet:</span></p>
      <p><strong><span>Name:&nbsp;</span></strong><span>csrftoken</span><br><strong><span>Wert:&nbsp;</span></strong><span>&ldquo;&rdquo;</span><br><strong><span>Verwendungszweck:</span></strong><strong><span>&nbsp;</span></strong><span>Dieses Cookie **** mit hoher Wahrscheinlichkeit aus Sicherheitsgr&uuml;**** gesetzt, um F&auml;lschungen *** Anfragen zu verhindern. Genauer ******* *** das allerdings nicht ** Erfahrung bringen.</span><br><strong><span>Ablaufdatum:</span></strong><span>&nbsp;**** einem Jahr</span></p>
      <p><strong><span>Name:&nbsp;</span></strong><span>mid</span><br><strong><span>Wert:&nbsp;</span></strong><span>&ldquo;&rdquo;</span><br><strong><span>Verwendungszweck:&nbsp;</span></strong><span>Instagram setzt dieses Cookie, um die eigenen Dienstleistungen und Angebote ** und au&szlig;erhalb von Instagram zu optimieren. Das Cookie legt eine eindeutige User-ID fest.</span><br><strong><span>Ablaufdatum:</span></strong><span>&nbsp;**** Ende der Sitzung</span></p>
      <p><strong><span>Name:</span></strong><span>&nbsp;fbsr_111735732124024</span><br><strong><span>Wert:&nbsp;</span></strong><span>keine Angaben</span><br><strong><span>Verwendungszweck:</span></strong><strong><span>&nbsp;</span></strong><span>Dieses Cookie speichert *** Log-in-******* f&uuml;r User der Instagram-App.</span><strong><span>&nbsp;</span></strong><br><strong><span>Ablaufdatum:</span></strong><span>&nbsp;**** Ende der Sitzung</span></p>
      <p><strong><span>Name:</span></strong><span>&nbsp;rur</span><br><strong><span>Wert:&nbsp;</span></strong><span>ATN</span><br><strong><span>Verwendungszweck:&nbsp;</span></strong><span>Dabei handelt es sich um ein Instagram-Cookie, das die Funktionalit&auml;t auf ********* gew&auml;hrleistet.</span><br><strong><span>Ablaufdatum:</span></strong><span>&nbsp;nach Ende der Sitzung</span></p>
      <p><strong><span>Name:</span></strong><span>&nbsp;urlgen</span><br><strong><span>Wert:&nbsp;</span></strong><span>&ldquo;{&rdquo;194.96.75.33&rdquo;: 1901}:1iEtYv:Y833k2_UjKvXgYe111735732&rdquo;</span><br><strong><span>Verwendungszweck:&nbsp;</span></strong><span>Dieses Cookie dient den Marketingzwecken von Instagram.</span><br><strong><span>Ablaufdatum:</span></strong><span>&nbsp;**** **** der Sitzung</span></p>
      <p><strong><span>Anmerkung:</span></strong><span>&nbsp;Wir k&ouml;nnen hier keinen Vollst&auml;ndigkeitsanspruch erheben. ****** Cookies ** individuellen Fall gesetzt werden, h&auml;*** von den eingebetteten Funktionen und Ihrer ********** von Instagram ab.</span></p>
      <p style="margin-top:14pt; margin-bottom:14pt; font-size:13.5pt;"><strong><span>Wie lange und wo werden die Daten gespeichert?</span></strong></p>
      <p><span>Instagram teilt die erhaltenen ************* zwischen den Facebook-Unternehmen mit externen ******** und mit Personen, mit denen *** sich weltweit verbinden. *** Datenverarbeitung erfolgt unter ********** der eigenen Datenrichtlinie. Ihre Daten sind, unter anderem *** Sicherheitsgr&uuml;nden, auf *** Facebook-******* auf der ganzen Welt verteilt. Die meisten dieser Server stehen in den USA.</span></p>
      <p style="margin-top:14pt; margin-bottom:14pt; font-size:13.5pt;"><strong><span>Wie **** ich meine ***** l&ouml;schen bzw. die Datenspeicherung verhindern?</span></strong></p>
      <p><span>Dank der *********** Grundverordnung haben Sie das ***** auf Auskunft, &Uuml;bertragbarkeit, ************ und L&ouml;schung ***** Daten. In den Instagram-Einstellungen k&ouml;nnen Sie Ihre ***** verwalten. Wenn Sie Ihre ***** auf Instagram v&ouml;**** l&ouml;schen wollen, m&uuml;ssen Sie Ihr Instagram-Konto dauerhaft l&ouml;schen.</span></p>
      <p><span>Und so funktioniert die L&ouml;****** des Instagram-Kontos:</span></p>
      <p><span>&Ouml;ffnen Sie zuerst die Instagram-App. Auf Ihrer Profilseite ***** Sie nach unten und klicken Sie auf &bdquo;Hilfebereich&ldquo;. Jetzt kommen Sie auf *** Webseite des Unternehmens. Klicken Sie auf der Webseite auf &bdquo;Verwalten *** Kontos&ldquo; und dann auf &bdquo;Dein Konto l&ouml;schen&ldquo;.</span></p>
      <p><span>**** Sie Ihr ***** ganz l&ouml;schen, l&ouml;scht Instagram Posts wie ************** Ihre Fotos und Status-Updates. Informationen, die andere Personen &uuml;ber *** geteilt haben, geh&ouml;ren nicht zu Ihrem Konto und werden ******** nicht gel&ouml;scht.</span></p>
      <p><span>Wie bereits oben erw&auml;hnt, speichert Instagram Ihre Daten in erster ***** &uuml;ber Cookies. Diese Cookies k&ouml;nnen Sie in Ihrem Browser verwalten, deaktivieren **** l&ouml;schen. Abh&auml;**** von Ihrem Browser funktioniert die Verwaltung immer ein bisschen anders. Hier zeigen wir Ihnen die Anleitungen der wichtigsten Browser.</span></p>
      <p><a href="https://support.google.com/chrome/answer/95647?tid=111735732" style="text-decoration:none;" target="_blank"><u><span style="font-family:'Times New Roman'; color:#0000ff;">Chrome: Cookies ** Chrome l&ouml;schen, ********** und verwalten</span></u></a><span>&nbsp;</span></p>
      <p><a href="https://support.apple.com/de-at/guide/safari/sfri11471/mac?tid=111735732" style="text-decoration:none;" target="_blank"><u><span style="font-family:'Times New Roman'; color:#0000ff;">Safari: ********* von Cookies *** Websitedaten mit Safari</span></u></a><span>&nbsp;</span></p>
      <p><a href="https://support.mozilla.org/de/kb/cookies-und-website-daten-in-firefox-loschen?tid=111735732" style="text-decoration:none;" target="_blank"><u><span style="font-family:'Times New Roman'; color:#0000ff;">Firefox: ******* l&ouml;schen, um Daten zu entfernen, die Websites auf Ihrem Computer abgelegt haben</span></u></a><span>&nbsp;</span></p>
      <p><a href="https://support.microsoft.com/de-at/help/17442/windows-internet-explorer-delete-manage-cookies?tid=111735732" style="text-decoration:none;" target="_blank"><u><span style="font-family:'Times New Roman'; color:#0000ff;">Internet Explorer: L&ouml;***** und Verwalten von Cookies</span></u></a><span>&nbsp;</span></p>
      <p><a href="https://support.microsoft.com/de-at/help/4027947/windows-delete-cookies?tid=111735732" style="text-decoration:none;" target="_blank"><u><span style="font-family:'Times New Roman'; color:#0000ff;">Microsoft Edge: L&ouml;schen und Verwalten von Cookies</span></u></a><span>&nbsp;</span></p>
      <p><span>*** k&ouml;**** auch grunds&auml;tzlich Ihren Browser so einrichten, dass Sie immer informiert werden, wenn ein Cookie ******* werden soll. Dann k&ouml;nnen Sie immer *********** entscheiden, ob Sie das ****** zulassen wollen oder nicht.</span></p>
      <p><span>Bitte beachten Sie, dass bei der Verwendung ****** Tools Daten von Ihnen **** au&szlig;erhalb der EU gespeichert und *********** werden k&ouml;nnen. Die meisten Drittstaaten (darunter auch die USA) gelten nach *********** europ&auml;ischen Datenschutzrecht *** nicht sicher. Daten an unsichere Drittstaaten d&uuml;rfen also nicht einfach &uuml;bertragen, **** gespeichert und *********** werden, ****** es keine passenden Garantien (wie etwa EU-Standardvertragsklauseln) zwischen uns und dem au&szlig;ereurop&auml;ischen ************* gibt.</span></p>
      <p><span>*** haben versucht, Ihnen *** wichtigsten Informationen &uuml;ber die Datenverarbeitung durch Instagram n&auml;herzubringen. Auf&nbsp;</span><a href="https://help.instagram.com/519522125107875" style="text-decoration:none;" target="_blank"><u><span style="font-family:'Times New Roman'; color:#0000ff;">https://help.instagram.com/519522125107875</span></u></a><span>&nbsp;</span><br><span>k&ouml;nnen Sie sich noch n&auml;*** mit den Datenrichtlinien von ********* auseinandersetzen.</span></p>
      <p style="margin-top:14pt; margin-bottom:14pt; font-size:18pt;"><strong><span>Google reCAPTCHA Datenschutzerkl&auml;rung</span></strong></p>
      <p><span>Unser ******** Ziel ist es, ****** ******** f&uuml;r *** und f&uuml;r uns bestm&ouml;***** zu ******* und ** sch&uuml;tzen. Um das zu gew&auml;hrleisten, verwenden wir Google reCAPTCHA der Firma Google Inc. F&uuml;r den europ&auml;ischen **** *** das Unternehmen Google Ireland Limited (Gordon House, Barrow ****** Dublin 4, Irland) f&uuml;r alle Google-Dienste verantwortlich. Mit reCAPTCHA k&ouml;nnen wir feststellen, ob Sie auch wirklich ein Mensch *** Fleisch und Blut sind und kein Roboter oder eine andere Spam-Software. Unter Spam verstehen wir jede, auf elektronischen Weg, unerw&uuml;****** Information, die uns ungefragter Weise zukommt. Bei den klassischen CAPTCHAS mussten Sie zur &Uuml;berpr&uuml;fung meist Text- oder Bildr&auml;tsel l&ouml;sen. Mit reCAPTCHA *** Google m&uuml;ssen wir Sie meist nicht mit solchen R&auml;tseln bel&auml;stigen. Hier reicht es in *** meisten F&auml;llen, wenn Sie einfach *** H&auml;kchen ****** *** so best&auml;tigen, dass Sie kein Bot sind. Mit der neuen Invisible reCAPTCHA ******* m&uuml;ssen Sie nicht mal mehr *** H&auml;kchen setzen. Wie das genau funktioniert und vor allem ****** Daten daf&uuml;r verwendet werden, erfahren Sie im Verlauf dieser Datenschutzerkl&auml;rung.</span></p>
      <p style="margin-top:14pt; margin-bottom:14pt; font-size:13.5pt;"><strong><span>*** ist reCAPTCHA?</span></strong></p>
      <p><span>reCAPTCHA ist ein freier Captcha-Dienst von Google, der Webseiten vor Spam-Software und den ********** durch nicht-menschliche Besucher sch&uuml;tzt. ** h&auml;ufigsten wird dieser Dienst verwendet, wenn Sie Formulare im Internet ausf&uuml;llen. Ein Captcha-Dienst ist eine Art automatischer Turing-Test, der ************* soll, dass **** Handlung im Internet von einem Menschen und nicht von einem Bot *********** wird. ** klassischen Turing-Test (benannt nach dem Informatiker Alan Turing) stellt *** Mensch die Unterscheidung ******** *** und Mensch fest. Bei Captchas &uuml;bernimmt das auch der Computer bzw. ein Softwareprogramm. ********** Captchas arbeiten *** ******* Aufgaben, die f&uuml;r Menschen leicht zu l&ouml;sen sind, doch f&uuml;r Maschinen ********** Schwierigkeiten aufweisen. Bei reCAPTCHA m&uuml;ssen *** aktiv keine R&auml;tsel mehr l&ouml;sen. Das Tool verwendet moderne Risikotechniken, um Menschen *** Bots zu unterscheiden. Hier m&uuml;ssen Sie nur **** das ******** &bdquo;Ich bin kein Roboter&ldquo; ********* bzw. bei Invisible reCAPTCHA *** selbst das nicht mehr n&ouml;tig. Bei reCAPTCHA wird ein JavaScript-Element in den Quelltext eingebunden und dann l&auml;uft das Tool im Hintergrund und analysiert Ihr Benutzerverhalten. Aus diesen ************ berechnet die Software einen sogenannten Captcha-Score. Google berechnet mit diesem Score schon *** der Captcha-Eingabe wie **** die Wahrscheinlichkeit ist, dass Sie ein Mensch sind. reCAPTCHA bzw. ******** im *********** kommen ***** dann *** Einsatz, wenn Bots gewisse Aktionen (wie z.B. Registrierungen, ******** usw.) ************ oder missbrauchen k&ouml;nnten.</span></p>
      <p style="margin-top:14pt; margin-bottom:14pt; font-size:13.5pt;"><strong><span>***** ********* wir reCAPTCHA auf unserer Webseite?</span></strong></p>
      <p><span>Wir ****** nur Menschen aus Fleisch und Blut auf unserer Seite begr&uuml;&szlig;en. Bots oder Spam-******** unterschiedlichster Art d&uuml;rfen getrost zuhause bleiben. ***** ****** wir alle ***** in Bewegung, uns zu sch&uuml;tzen und die bestm&ouml;gliche Benutzerfreundlichkeit f&uuml;r Sie anzubieten. Aus diesem Grund verwenden wir ****** reCAPTCHA der Firma Google. So k&ouml;nnen wir uns ******** sicher sein, dass wir eine &bdquo;botfreie&ldquo; Webseite bleiben. Durch die Verwendung von reCAPTCHA ****** Daten an Google &uuml;bermittelt, ** festzustellen, ob Sie **** wirklich ein Mensch sind. reCAPTCHA dient also der ********** ******* Webseite und in weiterer ***** damit auch ***** Sicherheit. Zum Beispiel k&ouml;nnte es **** reCAPTCHA passieren, **** bei ***** Registrierung ein Bot m&ouml;glichst viele E-Mail-Adressen registriert, um im Anschluss Foren oder Blogs mit unerw&uuml;nschten Werbeinhalten &bdquo;zuzuspamen&ldquo;. Mit reCAPTCHA k&ouml;nnen wir solche Botangriffe vermeiden.</span></p>
      <p style="margin-top:14pt; margin-bottom:14pt; font-size:13.5pt;"><strong><span>Welche Daten werden von reCAPTCHA gespeichert?</span></strong></p>
      <p><span>reCAPTCHA sammelt personenbezogene Daten von Usern, ** festzustellen, ob die Handlungen *** unserer Webseite auch wirklich von Menschen stammen. Es kann also die IP-Adresse und andere Daten, die Google f&uuml;r den reCAPTCHA-****** ben&ouml;tigt, an Google versendet werden. IP-Adressen werden innerhalb der Mitgliedstaaten *** EU oder anderer Vertragsstaaten des Abkommens &uuml;ber den Europ&auml;ischen Wirtschaftsraum **** immer zuvor gek&uuml;rzt, bevor die Daten auf einem Server in den USA landen. Die IP-Adresse wird nicht mit anderen Daten von ****** kombiniert, sofern Sie nicht w&auml;hrend der Verwendung von ********* mit Ihrem Google-Konto angemeldet sind. Zuerst pr&uuml;ft der reCAPTCHA-Algorithmus, ob auf Ihrem ******* schon Google-Cookies von anderen Google-Diensten (YouTube. Gmail usw.) platziert sind. Anschlie&szlig;end setzt reCAPTCHA ein zus&auml;******** Cookie in Ihrem ******* *** erfasst einen Schnappschuss Ihres Browserfensters.</span></p>
      <p><span>Die folgende Liste von gesammelten Browser- und Userdaten, hat ***** den Anspruch *** Vollst&auml;ndigkeit. Vielmehr sind es Beispiele von Daten, die nach unserer Erkenntnis, *** Google verarbeitet werden.</span></p>
      <ul style="margin:0pt; padding-left:0pt;" type="disc">
        <li style="margin-top:14pt; margin-left:27.6pt; padding-left:8.4pt; font-family:serif; font-size:10pt;"><span style="font-family:'Times New Roman'; font-size:12pt;">Referrer URL (*** Adresse der Seite von der der Besucher kommt)</span></li>
        <li style="margin-left:27.6pt; padding-left:8.4pt; font-family:serif; font-size:10pt;"><span style="font-family:'Times New Roman'; font-size:12pt;">IP-Adresse (z.B. 256.123.123.1)</span></li>
        <li style="margin-left:27.6pt; padding-left:8.4pt; font-family:serif; font-size:10pt;"><span style="font-family:'Times New Roman'; font-size:12pt;">Infos &uuml;ber das Betriebssystem</span><span style="font-family:'Times New Roman'; font-size:12pt;">&nbsp;</span><span style="font-family:'Times New Roman'; font-size:12pt;">(*** Software, *** den Betrieb Ihres Computers erm&ouml;glicht. Bekannte Betriebssysteme sind Windows, Mac OS X oder Linux)</span></li>
        <li style="margin-left:27.6pt; padding-left:8.4pt; font-family:serif; font-size:10pt;"><span style="font-family:'Times New Roman'; font-size:12pt;">Cookies</span><span style="font-family:'Times New Roman'; font-size:12pt;">&nbsp;</span><span style="font-family:'Times New Roman'; font-size:12pt;">(****** Textdateien, die ***** in ***** Browser speichern)</span></li>
        <li style="margin-left:27.6pt; padding-left:8.4pt; font-family:serif; font-size:10pt;"><span style="font-family:'Times New Roman'; font-size:12pt;">Maus- und Keyboardverhalten</span><span style="font-family:'Times New Roman'; font-size:12pt;">&nbsp;</span><span style="font-family:'Times New Roman'; font-size:12pt;">(jede Aktion, die Sie mit der Maus oder der Tastatur ausf&uuml;**** wird gespeichert)</span></li>
        <li style="margin-left:27.6pt; padding-left:8.4pt; font-family:serif; font-size:10pt;"><span style="font-family:'Times New Roman'; font-size:12pt;">Datum und Spracheinstellungen</span><span style="font-family:'Times New Roman'; font-size:12pt;">&nbsp;</span><span style="font-family:'Times New Roman'; font-size:12pt;">(welche Sprache bzw. welches Datum Sie auf Ihrem PC voreingestellt haben wird gespeichert)</span></li>
        <li style="margin-left:27.6pt; padding-left:8.4pt; font-family:serif; font-size:10pt;"><span style="font-family:'Times New Roman'; font-size:12pt;">Alle Javascript-Objekte</span><span style="font-family:'Times New Roman'; font-size:12pt;">&nbsp;</span><span style="font-family:'Times New Roman'; font-size:12pt;">(JavaScript ist eine Programmiersprache, die Webseiten erm&ouml;glicht, sich an den User anzupassen. JavaScript-Objekte k&ouml;nnen alle m&ouml;glichen Daten ***** einem Namen sammeln)</span></li>
        <li style="margin-left:27.6pt; margin-bottom:14pt; padding-left:8.4pt; font-family:serif; font-size:10pt;"><span style="font-family:'Times New Roman'; font-size:12pt;">Bildschirmaufl&ouml;sung</span><span style="font-family:'Times New Roman'; font-size:12pt;">&nbsp;</span><span style="font-family:'Times New Roman'; font-size:12pt;">(zeigt an aus wie vielen Pixeln die Bilddarstellung besteht)</span></li>
      </ul>
      <p><span>************ ist, **** Google diese Daten verwendet und analysiert **** ***** *** auf das H&auml;***** &bdquo;Ich bin kein Roboter&ldquo; klicken. Bei der Invisible reCAPTCHA-Version f&auml;*** sogar das Ankreuzen *** und der ganze Erkennungsprozess l&auml;uft im Hintergrund ab. Wie viel und ****** Daten Google genau speichert, erf&auml;hrt man von Google nicht im Detail.</span></p>
      <p><span>Folgende Cookies werden von reCAPTCHA verwendet: Hierbei ******** wir *** auf die reCAPTCHA Demo-Version von Google unter&nbsp;</span><a href="https://www.google.com/recaptcha/api2/demo" style="text-decoration:none;" target="_blank"><u><span style="font-family:'Times New Roman'; color:#0000ff;">https://www.google.com/recaptcha/api2/demo</span></u></a><span>. All ***** Cookies ben&ouml;tigen zu *************** eine eindeutige Kennung. Hier ist eine Liste an Cookies, die ****** reCAPTCHA auf der Demo-Version gesetzt hat:</span></p>
      <p><strong><span>Name:</span></strong><span>&nbsp;IDE</span><br><strong><span>Wert:</span></strong><span>&nbsp;</span><span>WqTUmlnmv_qXyi_DGNPLESKnRNrpgXoy1K-pAZtAkMbHI-111735732-8</span><br><strong><span>Verwendungszweck:</span></strong><span>&nbsp;Dieses Cookie wird von der Firma DoubleClick (geh&ouml;rt **** Google) gesetzt, um die ******** ***** Users auf der Webseite im Umgang mit Werbeanzeigen zu registrieren und zu melden. So kann die Werbewirksamkeit gemessen und entsprechende Optimierungsma&szlig;****** getroffen werden. IDE wird in Browsern unter der Domain doubleclick.net gespeichert.</span><br><strong><span>Ablaufdatum:</span></strong><span>&nbsp;nach einem Jahr</span></p>
      <p><strong><span>Name:</span></strong><span>&nbsp;1P_JAR</span><br><strong><span>Wert:</span></strong><span>&nbsp;</span><span>2019-5-14-12</span><br><strong><span>Verwendungszweck:</span></strong><span>&nbsp;Dieses Cookie ******* Statistiken zur Webseite-******* *** misst Conversions. Eine Conversion entsteht z.B., wenn ein User ** einem K&auml;ufer wird. Das Cookie wird **** verwendet, ** Usern relevante Werbeanzeigen einzublenden. Weiters kann man *** dem Cookie vermeiden, dass ein User dieselbe Anzeige mehr als einmal ** Gesicht bekommt.</span><br><strong><span>Ablaufdatum:</span></strong><span>&nbsp;nach einem Monat</span></p>
      <p><strong><span>Name:</span></strong><span>&nbsp;ANID</span><br><strong><span>Wert:</span></strong><span>&nbsp;</span><span>U7j1v3dZa1117357320xgZFmiqWppRWKOr</span><br><strong><span>Verwendungszweck:</span></strong><span>&nbsp;***** Infos konnten wir &uuml;*** dieses Cookie nicht in ********* bringen. In *** Datenschutzerkl&auml;rung von Google wird *** Cookie im Zusammenhang *** &bdquo;Werbecookies&ldquo; wie z. B. &ldquo;DSID&rdquo;, &ldquo;FLC&rdquo;, &ldquo;AID&rdquo;, &ldquo;TAID&rdquo; erw&auml;hnt. ANID wird unter Domain google.com gespeichert.</span><br><strong><span>Ablaufdatum:</span></strong><span>&nbsp;nach 9 Monaten</span></p>
      <p><strong><span>Name:</span></strong><span>&nbsp;CONSENT</span><br><strong><span>Wert:</span></strong><strong><span>&nbsp;</span></strong><span>YES+AT.de+20150628-20-0</span><br><strong><span>Verwendungszweck:</span></strong><span>&nbsp;Das Cookie speichert den Status der Zustimmung eines Users zur Nutzung unterschiedlicher Services von Google. CONSENT dient auch der Sicherheit, ** User zu &uuml;berpr&uuml;fen, Betr&uuml;gereien von Anmeldeinformationen zu ********** *** Userdaten vor unbefugten Angriffen zu sch&uuml;tzen.</span><br><strong><span>Ablaufdatum:</span></strong><span>&nbsp;nach 19 Jahren</span></p>
      <p><strong><span>Name:</span></strong><span>&nbsp;NID</span><br><strong><span>Wert:</span></strong><span>&nbsp;0WmuWqy111735732zILzqV_nmt3sDXwPeM5Q</span><br><strong><span>Verwendungszweck:</span></strong><span>&nbsp;NID wird *** Google verwendet, um Werbeanzeigen an **** Google-Suche anzupassen. Mit Hilfe *** Cookies &bdquo;erinnert&ldquo; **** Google an Ihre meist eingegebenen Suchanfragen oder Ihre fr&uuml;here *********** mit Anzeigen. So bekommen Sie immer ma&szlig;geschneiderte Werbeanzeigen. Das Cookie enth&auml;lt eine einzigartige ID, um pers&ouml;nliche Einstellungen des Users f&uuml;r Werbezwecke zu sammeln.</span><br><strong><span>Ablaufdatum:</span></strong><span>&nbsp;nach 6 Monaten</span></p>
      <p><strong><span>Name:</span></strong><span>&nbsp;DV</span><br><strong><span>Wert:</span></strong><span>&nbsp;gEAABBCjJMXcI0dSAAAANbqc111735732-4</span><br><strong><span>Verwendungszweck:</span></strong><span>&nbsp;Sobald Sie das &bdquo;Ich bin kein Roboter&ldquo;-H&auml;***** angekreuzt haben, wird ****** Cookie gesetzt. Das Cookie wird von Google Analytics f&uuml;r personalisierte Werbung verwendet. ** sammelt Informationen in anonymisierter Form und wird weiters benutzt, um User-Unterscheidungen zu treffen.</span><br><strong><span>Ablaufdatum:</span></strong><span>&nbsp;**** 10 Minuten</span></p>
      <p><strong><span>Anmerkung:</span></strong><strong><span>&nbsp;</span></strong><span>Diese Aufz&auml;hlung kann keinen ******** auf Vollst&auml;******** erheben, ** Google erfahrungsgem&auml;&szlig; die Wahl ihrer Cookies immer wieder **** ver&auml;ndert.</span></p>
      <p style="margin-top:14pt; margin-bottom:14pt; font-size:13.5pt;"><strong><span>Wie lange und wo ****** *** Daten gespeichert?</span></strong></p>
      <p><span>Durch das Einf&uuml;gen von reCAPTCHA werden Daten von Ihnen *** den Google-Server &uuml;bertragen. Wo genau diese Daten gespeichert werden, stellt Google, selbst nach wiederholtem Nachfragen, ***** klar dar. Ohne eine Best&auml;tigung von Google erhalten zu haben, ist davon auszugehen, dass Daten wie Mausinteraktion, Verweildauer auf der Webseite oder ******************* auf den europ&auml;ischen oder amerikanischen Google-Servern gespeichert werden. Die IP-Adresse, die Ihr ******* ** Google &uuml;bermittelt, **** grunds&auml;tzlich nicht mit anderen Google-***** aus weiteren Google-Diensten zusammengef&uuml;hrt. Wenn *** allerdings w&auml;hrend der Nutzung *** reCAPTCHA-Plug-ins bei Ihrem Google-Konto angemeldet sind, werden die Daten zusammengef&uuml;hrt.</span><strong><span>&nbsp;</span></strong><span>Daf&uuml;r gelten die abweichenden Datenschutzbestimmungen der Firma Google.</span></p>
      <p style="margin-top:14pt; margin-bottom:14pt; font-size:13.5pt;"><strong><span>Wie kann ich meine Daten l&ouml;schen bzw. die Datenspeicherung verhindern?</span></strong></p>
      <p><span>**** Sie wollen, dass &uuml;ber *** *** &uuml;ber Ihr Verhalten keine Daten ** Google &uuml;bermittelt werden, m&uuml;ssen Sie sich, bevor Sie unsere Webseite besuchen bzw. die reCAPTCHA-Software verwenden, bei Google vollkommen ausloggen und alle Google-******* l&ouml;schen.</span><span>&nbsp;</span><span>Grunds&auml;****** werden die Daten sobald Sie unsere Seite aufrufen *********** an Google &uuml;bermittelt. Um diese Daten wieder zu l&ouml;schen, m&uuml;**** Sie den Google-Support auf</span><span>&nbsp;</span><span>&nbsp;</span><a href="https://support.google.com/?hl=de&tid=111735732" style="text-decoration:none;" target="_blank"><u><span style="font-family:'Times New Roman'; color:#0000ff;">https://support.google.com/?hl=de&amp;tid=111735732</span></u></a><span>&nbsp;kontaktieren.</span></p>
      <p><span>Wenn Sie also unsere Webseite verwenden, erkl&auml;*** Sie sich einverstanden, **** Google LLC und deren Vertreter automatisch Daten erheben, bearbeiten *** nutzen.</span></p>
      <p><span>Bitte beachten Sie, **** bei der Verwendung dieses Tools Daten von Ihnen auch au&szlig;erhalb der EU *********** *** verarbeitet werden k&ouml;nnen. Die meisten Drittstaaten (darunter auch die USA) gelten nach derzeitigem europ&auml;ischen Datenschutzrecht als nicht sicher. Daten an unsichere Drittstaaten d&uuml;rfen also nicht einfach &uuml;bertragen, dort gespeichert und verarbeitet werden, sofern es ***** ********* Garantien (wie etwa EU-Standardvertragsklauseln) ******** uns und dem au&szlig;ereurop&auml;ischen ************* gibt.</span></p>
      <p><span>Etwas mehr &uuml;ber reCAPTCHA erfahren Sie auf der Webentwickler-Seite von Google auf&nbsp;</span><a href="https://developers.google.com/recaptcha/" style="text-decoration:none;" target="_blank"><u><span style="font-family:'Times New Roman'; color:#0000ff;">https://developers.google.com/recaptcha/</span></u></a><span>. Google **** hier zwar auf die ********** Entwicklung der reCAPTCHA n&auml;her ein, **** genaue Informationen &uuml;ber Datenspeicherung und datenschutzrelevanten Themen ***** man auch dort vergeblich. Eine **** &Uuml;******** &uuml;ber die grunds&auml;******* Verwendung von Daten bei Google finden Sie in der hauseigenen Datenschutzerkl&auml;rung auf&nbsp;</span><a href="https://policies.google.com/privacy?hl=de&tid=111735732" style="text-decoration:none;" target="_blank"><u><span style="font-family:'Times New Roman'; color:#0000ff;">https://www.google.com/intl/de/policies/privacy/</span></u></a><span>.</span></p>
      <p style="margin-top:0pt; margin-bottom:0pt; font-size:12pt;"><span>Alle Texte sind urheberrechtlich gesch&uuml;tzt.</span></p>
      <p style="margin-top:11.25pt; margin-bottom:14pt; font-size:12pt;"><span>Quelle: Erstellt *** dem&nbsp;</span><a href="https://www.adsimple.at/datenschutz-generator/" style="text-decoration:none;" title="Datenschutz Generator von AdSimple"><u><span style="font-family:'Times New Roman'; color:#0000ff;">Datenschutz Generator</span></u></a><span>&nbsp;*** AdSimple</span></p>
      <p style="margin-top:0pt; margin-bottom:8pt; line-height:108%; font-size:11pt;"><span style="font-family:Calibri;">&nbsp;</span></p>
    </div>
  </div>
</template>

<script>
export default {
  name: "Dataprivacy"
}
</script>

<style scoped lang="scss">
@use "src/assets/styles/colors";
img.crop-center {
  height: 250px;
  width: 100% !important;
  object-fit: cover;
  object-position: bottom center;
}

.u1 {
  font-family: dinosaur, sans-serif;
  font-weight: 200;
  font-style: initial;
  font-size: 55px;
  padding-left: 1em;
  padding-top: 0.5em;
  letter-spacing: 2.5px;
  color: colors.$fourth;
}

.text{
  font-family: dinosaur, sans-serif;
  font-weight: 200;
  font-style: initial;
  font-size: 25px;
  padding-left: 200px;
  padding-right: 200px;
}

</style>